import { PromoCodeItem } from './types';

export const INITIAL_PROMOS: PromoCodeItem[] = [
  {
    id: 'p-1',
    code: 'WELCOME10',
    title: 'First-Time Client Welcome Offer',
    description: 'Get 10% instant discount on your first companion booking session anywhere worldwide.',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    discountPercent: 10,
    flatDiscount: 0,
    minBookingAmount: 100,
    maxDiscountLimit: 50,
    usageLimit: 2000,
    usageCount: 1420,
    validFrom: '2026-01-01',
    expiryDate: '2026-12-31',
    applicableCategories: ['All Categories'],
    isActive: true,
    isFeatured: true,
    createdAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'p-2',
    code: 'SAFETYFIRST',
    title: 'Verified Safe Venue Pass',
    description: 'Flat $20 discount when booking a companion at verified partner cafes and safe meetup zones.',
    discountType: 'FLAT_AMOUNT',
    discountValue: 20,
    discountPercent: 0,
    flatDiscount: 20,
    minBookingAmount: 150,
    usageLimit: 1000,
    usageCount: 890,
    validFrom: '2026-02-15',
    expiryDate: '2026-10-15',
    applicableCategories: ['Dining & Social', 'Safe Zone Meets'],
    isActive: true,
    isFeatured: true,
    createdAt: '2026-02-15T00:00:00Z'
  },
  {
    id: 'p-3',
    code: 'VIP2026',
    title: 'Exclusive VIP Gala & Concert Pass',
    description: 'Save 15% on high-end red carpet, gala, and VIP concert event escort companion bookings.',
    discountType: 'PERCENTAGE',
    discountValue: 15,
    discountPercent: 15,
    flatDiscount: 0,
    minBookingAmount: 300,
    maxDiscountLimit: 120,
    usageLimit: 500,
    usageCount: 310,
    validFrom: '2026-03-01',
    expiryDate: '2026-11-30',
    applicableCategories: ['VIP Events', 'Red Carpet'],
    isActive: true,
    isFeatured: true,
    createdAt: '2026-03-01T00:00:00Z'
  },
  {
    id: 'p-4',
    code: 'SUMMERGUEST',
    title: 'Global Travel Companion Pass',
    description: 'Flat $35 instant savings for multi-day travel companion bookings in Tier 1 destination cities.',
    discountType: 'FLAT_AMOUNT',
    discountValue: 35,
    discountPercent: 0,
    flatDiscount: 35,
    minBookingAmount: 400,
    usageLimit: 800,
    usageCount: 245,
    validFrom: '2026-06-01',
    expiryDate: '2026-09-30',
    applicableCategories: ['Travel & Tour', 'City Guide'],
    isActive: true,
    isFeatured: false,
    createdAt: '2026-06-01T00:00:00Z'
  },
  {
    id: 'p-5',
    code: 'NIGHTOUT',
    title: 'Weekend Nightlife Companion Discount',
    description: 'Enjoy 20% off weekend evening social gathering companion bookings.',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    discountPercent: 20,
    flatDiscount: 0,
    minBookingAmount: 200,
    maxDiscountLimit: 75,
    usageLimit: 300,
    usageCount: 295,
    validFrom: '2026-05-01',
    expiryDate: '2026-08-31',
    applicableCategories: ['Nightlife & Parties'],
    isActive: true,
    isFeatured: false,
    createdAt: '2026-05-01T00:00:00Z'
  }
];
