import { ServiceCategory } from './types';

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  {
    id: 'c-1',
    name: 'Events & Social',
    slug: 'events-social',
    description: 'Professional companion support for events, parties, weddings, conferences and social gatherings.',
    iconName: 'Users',
    bannerUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 1.2,
    minAgeLimit: 21,
    isFeatured: true,
    isActive: true,
    companionCount: 28,
    safetyPolicy: 'Public venues only. Mandatory emergency check-in every 2 hours.',
    createdAt: '2026-01-10',
    subcategories: [
      { id: 'sub-101', name: 'Event Companion', description: 'Professional setup & event presence assistance', basePrice: 80, requiredVerification: true },
      { id: 'sub-102', name: 'Wedding Companion', description: 'Elegant wedding guest & event assistant', basePrice: 90, requiredVerification: true },
      { id: 'sub-103', name: 'Party Companion', description: 'Lively, polite party companion & host assistance', basePrice: 75, requiredVerification: true },
      { id: 'sub-104', name: 'Birthday/Celebration Companion', description: 'Birthday & milestone celebration partner', basePrice: 70, requiredVerification: false },
      { id: 'sub-105', name: 'Corporate Event Companion', description: 'Corporate function & business event companion', basePrice: 95, requiredVerification: true },
      { id: 'sub-106', name: 'Conference Companion', description: 'Professional conference attendee & networking assistant', basePrice: 85, requiredVerification: true },
      { id: 'sub-107', name: 'Exhibition Companion', description: 'Trade show & exhibition companion', basePrice: 75, requiredVerification: false },
      { id: 'sub-108', name: 'Cultural Event Companion', description: 'Cultural program & festival companion', basePrice: 70, requiredVerification: false },
      { id: 'sub-109', name: 'Festival Companion', description: 'Music & traditional festival buddy', basePrice: 65, requiredVerification: false },
      { id: 'sub-110', name: 'Networking Event Companion', description: 'Professional networking & mixer partner', basePrice: 88, requiredVerification: true },
      { id: 'sub-111', name: 'Award/Business Event Companion', description: 'Gala award night & formal business event partner', basePrice: 100, requiredVerification: true }
    ]
  },
  {
    id: 'c-2',
    name: 'Travel & Exploration',
    slug: 'travel-exploration',
    description: 'Local guidance, road trips, sightseeing tours, and transit assistance.',
    iconName: 'Compass',
    bannerUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'MEDIUM',
    baseRateMultiplier: 1.15,
    minAgeLimit: 21,
    isFeatured: true,
    isActive: true,
    companionCount: 22,
    safetyPolicy: 'GPS live tracking enabled during city tours. Emergency SOS button active.',
    createdAt: '2026-01-15',
    subcategories: [
      { id: 'sub-201', name: 'Travel Companion', description: 'Long distance travel buddy & trip escort', basePrice: 85, requiredVerification: true },
      { id: 'sub-202', name: 'City Guide', description: 'In-depth local sightseeing & city neighborhood tour guide', basePrice: 77, requiredVerification: true },
      { id: 'sub-203', name: 'Local Experience', description: 'Authentic local culture & food exploration guide', basePrice: 70, requiredVerification: false },
      { id: 'sub-204', name: 'Sightseeing Companion', description: 'Monuments & heritage site tourist companion', basePrice: 65, requiredVerification: false },
      { id: 'sub-205', name: 'Road Trip Companion', description: 'Experienced driving & road trip companion', basePrice: 95, requiredVerification: true },
      { id: 'sub-206', name: 'Shopping Tour', description: 'Local market & shopping assistant', basePrice: 60, requiredVerification: false },
      { id: 'sub-207', name: 'Food Tour', description: 'Local street food & culinary walk companion', basePrice: 68, requiredVerification: false },
      { id: 'sub-208', name: 'Tourist Assistance', description: 'Navigational & language assistance for tourists', basePrice: 70, requiredVerification: true },
      { id: 'sub-209', name: 'Public Transport Assistance', description: 'Metro & city bus route navigation helper', basePrice: 50, requiredVerification: false },
      { id: 'sub-210', name: 'Airport Assistance', description: 'Airport pickup, baggage & terminal escort', basePrice: 90, requiredVerification: true },
      { id: 'sub-211', name: 'Train/Bus Travel Companion', description: 'Long-distance railway & interstate bus escort', basePrice: 80, requiredVerification: true },
      { id: 'sub-212', name: 'Photography Tour Companion', description: 'Scenic photo walk & camera assistant', basePrice: 75, requiredVerification: false },
      { id: 'sub-213', name: 'Adventure Trip Companion', description: 'Outdoor adventure & trekking buddy', basePrice: 100, requiredVerification: true }
    ]
  },
  {
    id: 'c-3',
    name: 'Care & Assistance',
    slug: 'care-assistance',
    description: 'Compassionate assistance for senior citizens, hospital visits, medical errands, and mobility.',
    iconName: 'Heart',
    bannerUrl: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 1.0,
    minAgeLimit: 22,
    isFeatured: true,
    isActive: true,
    companionCount: 19,
    safetyPolicy: 'Police verification & medical background check mandatory.',
    createdAt: '2026-02-01',
    subcategories: [
      { id: 'sub-301', name: 'Elderly Companion', description: 'Attentive care & companionship for senior citizens', basePrice: 86, requiredVerification: true },
      { id: 'sub-302', name: 'Hospital Companion', description: 'Escort & support during clinic or hospital visits', basePrice: 90, requiredVerification: true },
      { id: 'sub-303', name: 'Doctor Appointment Companion', description: 'Punctual escort for doctor consultation & checkups', basePrice: 75, requiredVerification: true },
      { id: 'sub-304', name: 'Medical Appointment Escort', description: 'Specialized escort for lab tests & medical procedures', basePrice: 85, requiredVerification: true },
      { id: 'sub-305', name: 'Pharmacy Visit Assistance', description: 'Help purchasing & collecting prescribed medicines', basePrice: 50, requiredVerification: false },
      { id: 'sub-306', name: 'Grocery Assistance', description: 'Assistance buying & carrying household groceries', basePrice: 55, requiredVerification: false },
      { id: 'sub-307', name: 'Daily Errand Assistance', description: 'Help with daily errands & routine tasks', basePrice: 60, requiredVerification: false },
      { id: 'sub-308', name: 'Accessibility Assistance', description: 'Dedicated mobility & wheelchair support assistant', basePrice: 85, requiredVerification: true },
      { id: 'sub-309', name: 'Walking Companion', description: 'Gentle outdoor walking & fresh air escort', basePrice: 45, requiredVerification: false },
      { id: 'sub-310', name: 'Reading/Conversation for Elderly', description: 'Reading books/newspapers & warm conversation for seniors', basePrice: 50, requiredVerification: false },
      { id: 'sub-311', name: 'Hospital Discharge Assistance', description: 'Support during hospital discharge & home return', basePrice: 95, requiredVerification: true },
      { id: 'sub-312', name: 'Government/Office Visit Assistance', description: 'Escort to government offices & administrative work', basePrice: 70, requiredVerification: true }
    ]
  },
  {
    id: 'c-4',
    name: 'Study, Career & Work',
    slug: 'study-career-work',
    description: 'Academic tutoring, library buddies, co-working, interview prep, and career strategy.',
    iconName: 'BookOpen',
    bannerUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 0.95,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 25,
    safetyPolicy: 'Public cafe / library co-working environments only.',
    createdAt: '2026-02-12',
    subcategories: [
      { id: 'sub-401', name: 'Study Buddy', description: 'Focused study partner & subject tutoring', basePrice: 60, requiredVerification: false },
      { id: 'sub-402', name: 'Library Companion', description: 'Quiet reading & library study partner', basePrice: 45, requiredVerification: false },
      { id: 'sub-403', name: 'Co-working Buddy', description: 'Productivity partner for co-working & remote work', basePrice: 65, requiredVerification: false },
      { id: 'sub-404', name: 'Online Study Partner', description: 'Virtual study session & accountability partner', basePrice: 50, requiredVerification: false },
      { id: 'sub-405', name: 'Exam Preparation Buddy', description: 'Competitive exam prep & revision partner', basePrice: 75, requiredVerification: false },
      { id: 'sub-406', name: 'Interview Practice Buddy', description: 'Mock interview practice & feedback session', basePrice: 85, requiredVerification: true },
      { id: 'sub-407', name: 'Career Discussion', description: 'Mentorship & career strategy brainstorming', basePrice: 90, requiredVerification: true },
      { id: 'sub-408', name: 'Resume Discussion', description: 'CV review & job application strategy buddy', basePrice: 70, requiredVerification: false },
      { id: 'sub-409', name: 'Professional Networking', description: 'Networking event partner & industry connector', basePrice: 88, requiredVerification: true },
      { id: 'sub-410', name: 'Conference/Business Meeting Companion', description: 'Formal business meeting companion', basePrice: 100, requiredVerification: true },
      { id: 'sub-411', name: 'Project Discussion Buddy', description: 'Brainstorming & technical project review partner', basePrice: 80, requiredVerification: false },
      { id: 'sub-412', name: 'Skill Practice Partner', description: 'Language, coding or presentation skill partner', basePrice: 70, requiredVerification: false }
    ]
  },
  {
    id: 'c-5',
    name: 'Fitness, Sports & Outdoor',
    slug: 'fitness-sports-outdoor',
    description: 'Workout spotting, running, cycling, sports partners, outdoor hiking and swimming.',
    iconName: 'Activity',
    bannerUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 1.05,
    minAgeLimit: 20,
    isFeatured: true,
    isActive: true,
    companionCount: 23,
    safetyPolicy: 'Verified outdoor trails or registered gym facilities.',
    createdAt: '2026-03-01',
    subcategories: [
      { id: 'sub-501', name: 'Walking Buddy', description: 'Casual park walking & daily step goal partner', basePrice: 45, requiredVerification: false },
      { id: 'sub-502', name: 'Running Partner', description: 'Pacing partner for morning or evening runs', basePrice: 65, requiredVerification: false },
      { id: 'sub-503', name: 'Jogging Partner', description: 'Cardio & endurance jogging partner', basePrice: 60, requiredVerification: false },
      { id: 'sub-504', name: 'Cycling Partner', description: 'Cycling buddy for city routes or scenic trails', basePrice: 70, requiredVerification: false },
      { id: 'sub-505', name: 'Gym Buddy', description: 'Gym workout spotting & weightlifting partner', basePrice: 75, requiredVerification: true },
      { id: 'sub-506', name: 'Yoga Partner', description: 'Outdoor yoga & stretching companion', basePrice: 60, requiredVerification: false },
      { id: 'sub-507', name: 'Badminton Partner', description: 'Racket sports & badminton match partner', basePrice: 70, requiredVerification: false },
      { id: 'sub-508', name: 'Cricket Partner', description: 'Net practice & casual cricket partner', basePrice: 65, requiredVerification: false },
      { id: 'sub-509', name: 'Football Partner', description: 'Turf football & shooting drill partner', basePrice: 75, requiredVerification: false },
      { id: 'sub-510', name: 'Basketball Partner', description: 'Court basketball 1v1 & practice buddy', basePrice: 70, requiredVerification: false },
      { id: 'sub-511', name: 'Swimming Companion', description: 'Pool swimming & water exercise companion', basePrice: 85, requiredVerification: true },
      { id: 'sub-512', name: 'Hiking Partner', description: 'Day hike & nature trail companion', basePrice: 90, requiredVerification: true },
      { id: 'sub-513', name: 'Trekking Companion', description: 'High altitude trekking & mountain trail escort', basePrice: 110, requiredVerification: true },
      { id: 'sub-514', name: 'Outdoor Activity Partner', description: 'General outdoor sports & adventure buddy', basePrice: 80, requiredVerification: false }
    ]
  },
  {
    id: 'c-6',
    name: 'Gaming & Entertainment',
    slug: 'gaming-entertainment',
    description: 'Co-op gaming, esports, movie companions, concert buddies, and live shows.',
    iconName: 'Gamepad',
    bannerUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'MEDIUM',
    baseRateMultiplier: 0.85,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 18,
    safetyPolicy: 'Online platform monitoring & chat moderation filters enabled.',
    createdAt: '2026-03-10',
    subcategories: [
      { id: 'sub-601', name: 'Gaming Buddy', description: 'Ranked FPS gaming partner & strategy coaching', basePrice: 70, requiredVerification: false },
      { id: 'sub-602', name: 'Multiplayer Gaming', description: 'Co-op multiplayer gaming squad partner', basePrice: 60, requiredVerification: false },
      { id: 'sub-603', name: 'Esports Partner', description: 'Competitive esports co-op & tournament partner', basePrice: 85, requiredVerification: false },
      { id: 'sub-604', name: 'Esports Practice', description: 'Dedicated scrimmage & esports practice partner', basePrice: 80, requiredVerification: false },
      { id: 'sub-605', name: 'Gaming Event Companion', description: 'LAN party & gaming expo companion', basePrice: 75, requiredVerification: false },
      { id: 'sub-606', name: 'Movie Companion', description: 'Cinema & movie theatre partner', basePrice: 55, requiredVerification: false },
      { id: 'sub-607', name: 'Theatre Companion', description: 'Drama, play & stage show companion', basePrice: 70, requiredVerification: false },
      { id: 'sub-608', name: 'Concert Companion', description: 'Live music festival & concert buddy', basePrice: 85, requiredVerification: true },
      { id: 'sub-609', name: 'Music Event Companion', description: 'Gig & live music venue partner', basePrice: 75, requiredVerification: false },
      { id: 'sub-610', name: 'Karaoke Companion', description: 'Fun karaoke night & singing companion', basePrice: 65, requiredVerification: false },
      { id: 'sub-611', name: 'Live Show Companion', description: 'Stand-up comedy & live performance companion', basePrice: 65, requiredVerification: false },
      { id: 'sub-612', name: 'Cultural Program Companion', description: 'Classical music & dance performance partner', basePrice: 70, requiredVerification: false }
    ]
  },
  {
    id: 'c-7',
    name: 'Social & Lifestyle',
    slug: 'social-lifestyle',
    description: 'Coffee conversations, dining partners, shopping companions, book discussions, and language practice.',
    iconName: 'Users',
    bannerUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 1.0,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 30,
    safetyPolicy: 'Public cafes, restaurants & commercial shopping malls only.',
    createdAt: '2026-03-15',
    subcategories: [
      { id: 'sub-701', name: 'Conversation Buddy', description: 'Engaging, friendly conversation & active listening', basePrice: 55, requiredVerification: false },
      { id: 'sub-702', name: 'Coffee Companion', description: 'Relaxing cafe & coffee hangout partner', basePrice: 50, requiredVerification: false },
      { id: 'sub-703', name: 'Dining Companion', description: 'Fine dining & culinary exploration partner', basePrice: 75, requiredVerification: false },
      { id: 'sub-704', name: 'Restaurant Companion', description: 'New restaurant opening & food tasting buddy', basePrice: 70, requiredVerification: false },
      { id: 'sub-705', name: 'Shopping Companion', description: 'Fashion, retail & personal shopping buddy', basePrice: 65, requiredVerification: false },
      { id: 'sub-706', name: 'Mall Companion', description: 'Casual mall walk & window shopping buddy', basePrice: 50, requiredVerification: false },
      { id: 'sub-707', name: 'Book Discussion', description: 'Literary & book analysis partner', basePrice: 50, requiredVerification: false },
      { id: 'sub-708', name: 'Reading Buddy', description: 'Book club & quiet reading companion', basePrice: 45, requiredVerification: false },
      { id: 'sub-709', name: 'Hobby Partner', description: 'Shared interest & pastime discussion partner', basePrice: 60, requiredVerification: false },
      { id: 'sub-710', name: 'Social Meetup', description: 'Community social meetup companion', basePrice: 55, requiredVerification: false },
      { id: 'sub-711', name: 'Local Social Activity', description: 'Neighborhood social event partner', basePrice: 60, requiredVerification: false },
      { id: 'sub-712', name: 'Language Practice Partner', description: 'Spoken English & foreign language practice buddy', basePrice: 65, requiredVerification: false }
    ]
  },
  {
    id: 'c-8',
    name: 'Pets & Hobbies',
    slug: 'pets-hobbies',
    description: 'Pet walking, photography companions, art, music practice, cooking, and gardening.',
    iconName: 'Heart',
    bannerUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 0.9,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 16,
    safetyPolicy: 'Pet handling safety protocols & verified outdoor spaces.',
    createdAt: '2026-03-20',
    subcategories: [
      { id: 'sub-801', name: 'Pet Walking', description: 'Daily dog walking & outdoor exercise escort', basePrice: 45, requiredVerification: false },
      { id: 'sub-802', name: 'Pet Companion', description: 'Loving pet care & playmate companion', basePrice: 55, requiredVerification: true },
      { id: 'sub-803', name: 'Vet Visit Companion', description: 'Escort & assistance for veterinary visits', basePrice: 65, requiredVerification: true },
      { id: 'sub-804', name: 'Pet Activity Partner', description: 'Pet park & agility activity companion', basePrice: 50, requiredVerification: false },
      { id: 'sub-805', name: 'Photography Companion', description: 'Outdoor photo shoot & camera assistant', basePrice: 80, requiredVerification: true },
      { id: 'sub-806', name: 'Photography Walk', description: 'City photo walk & landscape camera buddy', basePrice: 70, requiredVerification: false },
      { id: 'sub-807', name: 'Art Partner', description: 'Painting, sketching & art gallery companion', basePrice: 65, requiredVerification: false },
      { id: 'sub-808', name: 'Drawing Partner', description: 'Creative sketching & illustration partner', basePrice: 55, requiredVerification: false },
      { id: 'sub-809', name: 'Music Practice Partner', description: 'Instrument practice & music listening partner', basePrice: 70, requiredVerification: false },
      { id: 'sub-810', name: 'Instrument Practice Partner', description: 'Guitar/piano duet & rehearsal partner', basePrice: 75, requiredVerification: false },
      { id: 'sub-811', name: 'Cooking Hobby Partner', description: 'Culinary workshop & recipe experiment buddy', basePrice: 60, requiredVerification: false },
      { id: 'sub-812', name: 'Gardening Partner', description: 'Terrace garden & plant care partner', basePrice: 50, requiredVerification: false },
      { id: 'sub-813', name: 'Craft Partner', description: 'DIY craft, pottery & handmade art partner', basePrice: 55, requiredVerification: false }
    ]
  },
  {
    id: 'c-9',
    name: 'Technology & Digital',
    slug: 'technology-digital',
    description: 'Smartphone assistance, computer help, online forms, video calls, and digital payments.',
    iconName: 'Activity',
    bannerUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 1.1,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 15,
    safetyPolicy: 'Data privacy compliance & no credential sharing policy.',
    createdAt: '2026-03-25',
    subcategories: [
      { id: 'sub-901', name: 'Smartphone Assistance', description: 'Mobile app navigation & phone settings tutor', basePrice: 55, requiredVerification: false },
      { id: 'sub-902', name: 'Computer Assistance', description: 'PC/Mac software guidance & desktop support', basePrice: 75, requiredVerification: true },
      { id: 'sub-903', name: 'Basic Digital Help', description: 'General tech troubleshooting & device setup', basePrice: 60, requiredVerification: false },
      { id: 'sub-904', name: 'Online Form Assistance', description: 'Help filling out official digital forms & applications', basePrice: 65, requiredVerification: true },
      { id: 'sub-905', name: 'Digital Service Assistance', description: 'Online banking, portal & digital service guidance', basePrice: 70, requiredVerification: true },
      { id: 'sub-906', name: 'App/Website Guidance', description: 'Website navigation & smartphone app tutorial', basePrice: 50, requiredVerification: false },
      { id: 'sub-907', name: 'Video Call Assistance', description: 'Help setting up Zoom, WhatsApp & video calls', basePrice: 45, requiredVerification: false },
      { id: 'sub-908', name: 'Digital Payment Guidance', description: 'UPI & online payment safety tutorial', basePrice: 60, requiredVerification: true },
      { id: 'sub-909', name: 'Online Booking Assistance', description: 'Train, flight & event ticket booking help', basePrice: 55, requiredVerification: false },
      { id: 'sub-910', name: 'Basic Tech Learning', description: 'Patient step-by-step technology learning tutor', basePrice: 65, requiredVerification: false }
    ]
  },
  {
    id: 'c-10',
    name: 'Wellness & Mindfulness',
    slug: 'wellness-mindfulness',
    description: 'Meditation partners, yoga practice, nature walks, relaxation, and wellness activities.',
    iconName: 'Heart',
    bannerUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 1.0,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 18,
    safetyPolicy: 'Certified mindfulness practices & serene public park venues.',
    createdAt: '2026-04-01',
    subcategories: [
      { id: 'sub-1001', name: 'Meditation Buddy', description: 'Guided meditation & peaceful focus session buddy', basePrice: 60, requiredVerification: false },
      { id: 'sub-1002', name: 'Yoga Buddy', description: 'Outdoor yoga & mindfulness stretching partner', basePrice: 65, requiredVerification: false },
      { id: 'sub-1003', name: 'Nature Walk', description: 'Scenic park stroll & forest bathing companion', basePrice: 50, requiredVerification: false },
      { id: 'sub-1004', name: 'Mindfulness Partner', description: 'Mindful breathing & stress reduction companion', basePrice: 55, requiredVerification: false },
      { id: 'sub-1005', name: 'Relaxation Companion', description: 'Calm ambient relaxation & listening partner', basePrice: 50, requiredVerification: false },
      { id: 'sub-1006', name: 'Breathing Practice Partner', description: 'Pranayama & deep breathing exercise buddy', basePrice: 55, requiredVerification: false },
      { id: 'sub-1007', name: 'Wellness Activity Partner', description: 'Spa, wellness retreat & healthy lifestyle partner', basePrice: 75, requiredVerification: false },
      { id: 'sub-1008', name: 'Healthy Lifestyle Buddy', description: 'Nutrition & healthy habit accountability partner', basePrice: 60, requiredVerification: false },
      { id: 'sub-1009', name: 'Outdoor Relaxation', description: 'Park lounge & peaceful outdoor relaxation partner', basePrice: 45, requiredVerification: false },
      { id: 'sub-1010', name: 'Personal Development Discussion', description: 'Self-growth & goal planning discussion partner', basePrice: 70, requiredVerification: false }
    ]
  },
  {
    id: 'c-11',
    name: 'Home & Personal Assistance',
    slug: 'home-personal-assistance',
    description: 'Home errands, bank/post office visits, government office visits, and relocation help.',
    iconName: 'Users',
    bannerUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 1.0,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 20,
    safetyPolicy: 'Background check & verified identity mandatory for office visits.',
    createdAt: '2026-04-05',
    subcategories: [
      { id: 'sub-1101', name: 'Home Errand Companion', description: 'Assistance with domestic errands & routine chores', basePrice: 55, requiredVerification: false },
      { id: 'sub-1102', name: 'Grocery Assistance', description: 'Grocery shopping & heavy bag carrying support', basePrice: 50, requiredVerification: false },
      { id: 'sub-1103', name: 'Shopping Assistance', description: 'Household goods & personal shopping helper', basePrice: 55, requiredVerification: false },
      { id: 'sub-1104', name: 'Bank/Post Office Visit Companion', description: 'Escort for bank transactions & postal work', basePrice: 65, requiredVerification: true },
      { id: 'sub-1105', name: 'Government Office Visit Companion', description: 'Escort to municipality & public office tasks', basePrice: 75, requiredVerification: true },
      { id: 'sub-1106', name: 'Document Submission Assistance', description: 'Help delivering & submitting official paperwork', basePrice: 60, requiredVerification: true },
      { id: 'sub-1107', name: 'Queue/Appointment Assistance', description: 'Token collection & queue waiting support', basePrice: 50, requiredVerification: false },
      { id: 'sub-1108', name: 'Moving/Relocation Assistance', description: 'Packing, unpacking & relocation companion', basePrice: 85, requiredVerification: true },
      { id: 'sub-1109', name: 'Furniture/Appliance Shopping Companion', description: 'Showroom shopping & appliance selection partner', basePrice: 70, requiredVerification: false },
      { id: 'sub-1110', name: 'Home Service Appointment Companion', description: 'Presence during home technician & repair visits', basePrice: 60, requiredVerification: true },
      { id: 'sub-1111', name: 'Utility/Service Center Visit', description: 'Escort to electricity/water service centers', basePrice: 60, requiredVerification: false },
      { id: 'sub-1112', name: 'Local Errand Companion', description: 'General neighborhood errand companion', basePrice: 50, requiredVerification: false }
    ]
  },
  {
    id: 'c-12',
    name: 'Community & Volunteering',
    slug: 'community-volunteering',
    description: 'Community events, volunteer activities, NGO programs, charity drives, and cleanups.',
    iconName: 'Users',
    bannerUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&auto=format&fit=crop&q=80',
    riskLevel: 'LOW',
    baseRateMultiplier: 0.9,
    minAgeLimit: 18,
    isFeatured: true,
    isActive: true,
    companionCount: 16,
    safetyPolicy: 'Registered NGO & verified public community initiatives only.',
    createdAt: '2026-04-10',
    subcategories: [
      { id: 'sub-1201', name: 'Community Event Companion', description: 'Neighborhood gathering & community event partner', basePrice: 50, requiredVerification: false },
      { id: 'sub-1202', name: 'Social Activity Companion', description: 'Civic group & local club activity partner', basePrice: 55, requiredVerification: false },
      { id: 'sub-1203', name: 'Volunteer Activity Partner', description: 'Volunteering drive & social service buddy', basePrice: 45, requiredVerification: false },
      { id: 'sub-1204', name: 'NGO Event Companion', description: 'NGO awareness campaign & fundraiser companion', basePrice: 60, requiredVerification: true },
      { id: 'sub-1205', name: 'Charity/Fundraising Event Companion', description: 'Gala charity event & fundraising assistant', basePrice: 70, requiredVerification: true },
      { id: 'sub-1206', name: 'Community Cleanup Partner', description: 'Park & neighborhood environmental cleanup partner', basePrice: 40, requiredVerification: false },
      { id: 'sub-1207', name: 'Educational Community Activity', description: 'Teaching & youth literacy drive partner', basePrice: 55, requiredVerification: false },
      { id: 'sub-1208', name: 'Cultural Community Activity', description: 'Local heritage & cultural group partner', basePrice: 50, requiredVerification: false },
      { id: 'sub-1209', name: 'Local Community Meetup', description: 'Townhall & resident welfare meetup companion', basePrice: 45, requiredVerification: false },
      { id: 'sub-1210', name: 'Public Awareness Event Companion', description: 'Health & civic awareness rally companion', basePrice: 50, requiredVerification: false }
    ]
  }
];
