import {
  CategoryItem,
  ServiceItem,
  PricingProfile,
  RulesProfile,
  PolicyItem,
  RiskLevelItem,
  VerificationProfileItem,
  SafetyProfileItem,
  BookingRuleItem,
  EligibilityProfileItem
} from './types/serviceHub';

export const DEFAULT_PRICING_PROFILES: PricingProfile[] = [
  {
    id: 'pr-hourly-std',
    name: 'Standard Hourly Profile',
    pricing_type: 'Hourly',
    currency: 'INR',
    category_id: 'cat-2',
    category_name: 'Travel & Exploration',
    
    // 2. Rate & Duration
    base_price: 500,
    extra_hour_price: 450,
    minimum_duration: 1,
    maximum_duration: 12,

    // 3. Travel & Extra Charges
    travel_enabled: true,
    travel_pricing_type: 'Per KM',
    travel_charge: 15,
    free_distance_km: 5,
    max_travel_charge: 500,
    waiting_charge_per_hr: 100,
    parking_charge: 0,
    toll_charge: 0,
    other_charges: 0,

    // 4. Dynamic Pricing
    weekend_multiplier: 1.15,
    holiday_multiplier: 1.25,
    surge_enabled: true,
    surge_multiplier: 1.2,
    peak_hours_start: '18:00',
    peak_hours_end: '23:00',
    demand_pricing_multiplier: 1.1,
    surge_rules: {
      surge_multiplier: 1.2,
      peak_hours_start: '18:00',
      peak_hours_end: '23:00',
      demand_pricing_multiplier: 1.1,
      weekend_multiplier: 1.15,
      holiday_multiplier: 1.25,
      rule_name: 'Standard Peak Evening Surge Rule',
      status: 'ACTIVE'
    },

    // 5. Fees, Tax & Earnings
    platform_fee: 15,
    payment_gateway_fee: 2,
    tax: 18,
    companion_commission: 20,
    companion_payout_rate: 80,

    // 6. Discounts
    discount_enabled: true,
    discount_type: 'Percentage',
    discount_value: 10,
    discount_cap: 300,
    long_duration_discount: 5,

    // 7. Advanced & Versioning
    price_min_limit: 300,
    price_max_limit: 10000,
    rounding_rule: 'ROUND_NEAREST_10',
    version: 'v1.0',
    effective_from: '2026-01-01',
    pricing_snapshot_code: 'SNAP-V1.0-STD',
    historical_price_lock: true,
    cancellation_fee: 100,
    no_show_fee: 500,
    status: 'ACTIVE'
  },
  {
    id: 'pr-event-pro',
    name: 'Premium Event Package Profile',
    pricing_type: 'Per Event',
    currency: 'INR',
    category_id: 'cat-1',
    category_name: 'Events & Social',

    // 2. Rate & Duration
    base_price: 3500,
    extra_hour_price: 600,
    minimum_duration: 4,
    maximum_duration: 10,

    // 3. Travel & Extra Charges
    travel_enabled: true,
    travel_pricing_type: 'Fixed',
    travel_charge: 250,
    free_distance_km: 10,
    max_travel_charge: 1000,
    waiting_charge_per_hr: 200,
    parking_charge: 100,
    toll_charge: 50,
    other_charges: 0,

    // 4. Dynamic Pricing
    weekend_multiplier: 1.2,
    holiday_multiplier: 1.3,
    surge_enabled: false,
    surge_multiplier: 1.0,
    peak_hours_start: '19:00',
    peak_hours_end: '01:00',
    surge_rules: {
      surge_multiplier: 1.0,
      peak_hours_start: '19:00',
      peak_hours_end: '01:00',
      rule_name: 'Event Fixed Rate Surge Rule',
      status: 'INACTIVE'
    },

    // 5. Fees, Tax & Earnings
    platform_fee: 15,
    payment_gateway_fee: 2.5,
    tax: 18,
    companion_commission: 15,
    companion_payout_rate: 85,

    // 6. Discounts
    discount_enabled: true,
    discount_type: 'Fixed Amount',
    discount_value: 500,
    discount_cap: 500,
    long_duration_discount: 10,

    // 7. Advanced & Versioning
    price_min_limit: 2500,
    price_max_limit: 25000,
    rounding_rule: 'ROUND_NEAREST_50',
    version: 'v1.2',
    effective_from: '2026-01-01',
    pricing_snapshot_code: 'SNAP-V1.2-EVT',
    historical_price_lock: true,
    cancellation_fee: 500,
    no_show_fee: 1500,
    status: 'ACTIVE'
  },
  {
    id: 'pr-fixed-budget',
    name: 'Budget Fixed Profile',
    pricing_type: 'Fixed Price',
    currency: 'INR',
    category_id: 'cat-4',
    category_name: 'Study, Career & Work',

    // 2. Rate & Duration
    base_price: 350,
    extra_hour_price: 300,
    minimum_duration: 1,
    maximum_duration: 4,

    // 3. Travel & Extra Charges
    travel_enabled: false,
    travel_pricing_type: 'Per KM',
    travel_charge: 0,
    free_distance_km: 0,
    max_travel_charge: 0,
    waiting_charge_per_hr: 50,
    parking_charge: 0,
    toll_charge: 0,
    other_charges: 0,

    // 4. Dynamic Pricing
    weekend_multiplier: 1.0,
    holiday_multiplier: 1.1,
    surge_enabled: false,
    surge_multiplier: 1.0,

    // 5. Fees, Tax & Earnings
    platform_fee: 10,
    payment_gateway_fee: 2,
    tax: 18,
    companion_commission: 10,
    companion_payout_rate: 90,

    // 6. Discounts
    discount_enabled: false,
    discount_type: 'Percentage',
    discount_value: 0,
    discount_cap: 0,
    long_duration_discount: 0,

    // 7. Advanced & Versioning
    price_min_limit: 200,
    price_max_limit: 2000,
    rounding_rule: 'ROUND_NEAREST_10',
    version: 'v1.0',
    effective_from: '2026-01-01',
    pricing_snapshot_code: 'SNAP-V1.0-BDG',
    historical_price_lock: true,
    cancellation_fee: 50,
    no_show_fee: 200,
    status: 'ACTIVE'
  }
];

export const DEFAULT_RULES_PROFILES: RulesProfile[] = [
  {
    id: 'rl-std-safety',
    name: 'Standard Operational Rules',
    description: 'Basic duration, age, and location verification rules across categories',
    status: 'ACTIVE',
    rules: [
      {
        id: 'r-101',
        code: 'RULE-DUR-01',
        name: 'Duration Max Threshold',
        rule_type: 'Duration Rule',
        description: 'Bookings longer than 8 hours require explicit manager approval and guardian consent',
        priority: 1,
        scope_type: 'GLOBAL',
        category_name: 'All Categories',
        condition_group_operator: 'AND',
        conditions: [
          { id: 'c-1', field: 'duration_hours', operator: 'GREATER_THAN', value: 8, logical_operator: 'AND' }
        ],
        condition: 'duration_hours',
        operator: 'GREATER_THAN',
        value: 8,
        action: 'REQUIRE_APPROVAL',
        additional_requirements: ['IDENTITY_VERIFICATION', 'GUARDIAN_CONSENT'],
        approval_level: 'MANAGER_REVIEW',
        restriction_message: 'High duration booking requires Operations Manager manual approval.',
        risk_level_required: 'HIGH',
        verification_required: true,
        allow_override: true,
        override_role: 'OPERATIONS_MANAGER',
        validity_start: '2026-01-01',
        validity_end: '2026-12-31',
        escalation_action: 'Escalate to Safety Support Desk if unapproved after 2 hours',
        version: 'v1.2',
        severity: 'HIGH',
        status: 'ACTIVE',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-02-15T00:00:00.000Z',
        audit_history: [
          { timestamp: '2026-01-01 10:00', action: 'CREATE', author: 'System Admin', note: 'Created initial duration safety rule' },
          { timestamp: '2026-02-15 14:30', action: 'UPDATE', author: 'Safety Lead', note: 'Updated threshold to 8 hours & added manager review requirement' }
        ]
      },
      {
        id: 'r-102',
        code: 'RULE-LOC-02',
        name: 'Live GPS Location Requirement',
        rule_type: 'Location Rule',
        description: 'Mandatory live GPS streaming during offline sessions for companion safety',
        priority: 2,
        scope_type: 'GLOBAL',
        category_name: 'All Categories',
        condition_group_operator: 'AND',
        conditions: [
          { id: 'c-2', field: 'live_location_enabled', operator: 'EQUALS', value: false, logical_operator: 'AND' }
        ],
        condition: 'live_location_enabled',
        operator: 'EQUALS',
        value: false,
        action: 'BLOCK',
        additional_requirements: ['GPS_TRACKING', 'EMERGENCY_CONTACT'],
        approval_level: 'SYSTEM_AUTO',
        restriction_message: 'Session cannot start without enabling active GPS location sharing.',
        risk_level_required: 'CRITICAL',
        verification_required: true,
        allow_override: false,
        validity_start: '2026-01-01',
        version: 'v1.0',
        severity: 'CRITICAL',
        status: 'ACTIVE',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        audit_history: [
          { timestamp: '2026-01-01 10:00', action: 'CREATE', author: 'System Admin', note: 'Created mandatory GPS location policy' }
        ]
      },
      {
        id: 'r-103',
        code: 'RULE-SAF-03',
        name: 'High Value Booking Escort Restriction',
        rule_type: 'Safety Rule',
        description: 'Bookings over ₹5,000 require full government ID verification before confirmation',
        priority: 3,
        scope_type: 'CATEGORY',
        category_id: 'cat-1',
        category_name: 'Events & Social',
        condition_group_operator: 'AND',
        conditions: [
          { id: 'c-3', field: 'booking_amount', operator: 'GREATER_THAN', value: 5000, logical_operator: 'AND' }
        ],
        condition: 'booking_amount',
        operator: 'GREATER_THAN',
        value: 5000,
        action: 'REQUIRE_APPROVAL',
        additional_requirements: ['GOVT_ID_VERIFICATION', 'FACE_MATCH'],
        approval_level: 'ADMIN_MANUAL',
        restriction_message: 'High value event booking requires verified Govt ID badge.',
        risk_level_required: 'MEDIUM',
        verification_required: true,
        allow_override: true,
        override_role: 'SUPER_ADMIN',
        validity_start: '2026-01-01',
        version: 'v1.1',
        severity: 'MEDIUM',
        status: 'ACTIVE',
        createdAt: '2026-01-10T00:00:00.000Z',
        updatedAt: '2026-02-01T00:00:00.000Z',
        audit_history: [
          { timestamp: '2026-01-10 12:00', action: 'CREATE', author: 'Compliance Lead', note: 'Added high value transaction safety rule' }
        ]
      }
    ]
  }
];

export const DEFAULT_POLICIES: PolicyItem[] = [
  {
    id: 'pol-gen-01',
    code: 'POL-GEN-01',
    name: 'General Platform Eligibility Policy',
    policy_domain: 'General',
    description: 'General user eligibility, age verification 18+, and allowed categories rules',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    version: 1,
    status: 'PUBLISHED',
    effective_from: '2026-01-01T00:00:00.000Z',
    eligibility_text: 'Active Govt ID Verified Users aged 18+ with clear background check.',
    minimum_age: 18,
    kyc_required: true,
    background_check_required: true,
    consent_required: true,
    allowed_categories_text: 'Events & Social, Travel & Exploration, Fitness & Shopping',
    time_location_rules_text: 'Public locations between 06:00 to 23:00 hours.',
    general_restrictions_text: 'No unverified private residential meetings.',
    public_location_only: true,
    live_location_required: true,
    sos_required: true,
    emergency_contact_required: true,
    chat_moderation_required: true,
    incident_reporting_enabled: true,
    enforcement_type: 'STRICT_BLOCK',
    approval_status: 'APPROVED',
    approved_by: 'Compliance Desk',
    versions: [
      { version: 1, effective_from: '2026-01-01T00:00:00.000Z', description: 'Initial General Eligibility Policy', published_by: 'Compliance Team' }
    ]
  },
  {
    id: 'pol-bkg-02',
    code: 'POL-BKG-02',
    name: 'Booking Duration & Advance Notice Policy',
    policy_domain: 'Booking',
    description: 'Booking limits (1h to 12h), advance notice 2h, same-day rules, and deposit requirements',
    scope_type: 'CATEGORY',
    category_id: 'cat-1',
    category_name: 'Events & Social',
    version: 1,
    status: 'PUBLISHED',
    effective_from: '2026-01-01T00:00:00.000Z',
    min_duration_hours: 1,
    max_duration_hours: 12,
    advance_booking_hours: 2,
    same_day_booking_allowed: true,
    approval_required_for_booking: true,
    extension_allowed: true,
    rescheduling_allowed: true,
    payment_requirement: 'FULL_ADVANCE',
    minimum_age: 18,
    kyc_required: true,
    background_check_required: false,
    consent_required: true,
    public_location_only: true,
    live_location_required: true,
    sos_required: true,
    emergency_contact_required: true,
    chat_moderation_required: true,
    incident_reporting_enabled: true,
    enforcement_type: 'WARNING_ACKNOWLEDGEMENT',
    approval_status: 'APPROVED',
    approved_by: 'Operations Desk',
    versions: [
      { version: 1, effective_from: '2026-01-01T00:00:00.000Z', description: 'Initial Booking Rules Policy', published_by: 'Ops Team' }
    ]
  },
  {
    id: 'pol-saf-03',
    code: 'POL-SAF-03',
    name: 'Live GPS & Emergency SOS Safety Policy',
    policy_domain: 'Safety',
    description: 'Mandatory live GPS tracking, 30-min periodic check-ins, SOS panic button, and escalation timer',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    version: 1,
    status: 'PUBLISHED',
    effective_from: '2026-01-01T00:00:00.000Z',
    public_location_only: true,
    live_location_required: true,
    check_in_out_required: true,
    periodic_check_in_interval_mins: 30,
    sos_required: true,
    emergency_contact_required: true,
    night_booking_restricted: true,
    restricted_locations_text: 'Unlit isolated areas, unverified private residences',
    auto_sos_escalation_minutes: 5,
    minimum_age: 18,
    kyc_required: true,
    background_check_required: true,
    consent_required: true,
    chat_moderation_required: true,
    incident_reporting_enabled: true,
    enforcement_type: 'STRICT_BLOCK',
    approval_status: 'APPROVED',
    approved_by: 'Chief Safety Officer',
    versions: [
      { version: 1, effective_from: '2026-01-01T00:00:00.000Z', description: 'Initial Safety & SOS Policy', published_by: 'Safety Team' }
    ]
  },
  {
    id: 'pol-cnd-04',
    code: 'POL-CND-04',
    name: 'Conduct, Communication & Zero-Tolerance Policy',
    policy_domain: 'Conduct & Restrictions',
    description: 'Code of conduct for companion & customer, prohibited activities, and zero-tolerance violations',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    version: 1,
    status: 'PUBLISHED',
    effective_from: '2026-01-01T00:00:00.000Z',
    companion_rules_text: 'Professional decorum, punctual check-in, active GPS sharing, respectful boundaries.',
    customer_rules_text: 'Respectful conduct, public meeting places only, no coercion or illegal requests.',
    prohibited_activity_text: 'Strictly zero tolerance for harassment, substance abuse, physical coercion, or illegal activity.',
    restricted_services_text: 'No private unverified overnight stays or non-public locations.',
    communication_rules_text: 'All messaging must happen through in-app moderated chat.',
    zero_tolerance_violations_text: 'Immediate account ban and legal escalation upon violation report.',
    minimum_age: 18,
    kyc_required: true,
    background_check_required: true,
    consent_required: true,
    public_location_only: true,
    live_location_required: true,
    sos_required: true,
    emergency_contact_required: true,
    chat_moderation_required: true,
    incident_reporting_enabled: true,
    enforcement_type: 'STRICT_BLOCK',
    approval_status: 'APPROVED',
    approved_by: 'Legal & Conduct Desk',
    versions: [
      { version: 1, effective_from: '2026-01-01T00:00:00.000Z', description: 'Initial Conduct Code Policy', published_by: 'Legal Team' }
    ]
  },
  {
    id: 'pol-can-05',
    code: 'POL-CAN-05',
    name: 'Cancellation, No-Show & Incident Dispute Policy',
    policy_domain: 'Cancellation & Disputes',
    description: 'Rules for customer/companion cancellations, no-show fees, refund schedules, and dispute resolution',
    scope_type: 'CATEGORY',
    category_id: 'cat-2',
    category_name: 'Travel & Exploration',
    version: 1,
    status: 'PUBLISHED',
    effective_from: '2026-01-01T00:00:00.000Z',
    customer_cancellation_rules_text: 'Full refund if cancelled > 4h before booking; 50% refund within 2h to 4h.',
    companion_cancellation_rules_text: 'Companion cancellation incurs penalty score and instant reassignment.',
    no_show_policy_text: 'No-show after 20 mins grace period incurs 100% booking charge.',
    refund_rules_text: 'Processed back to original payment method within 3-5 business days.',
    complaint_protocol_text: 'Report via app within 24 hours of booking completion.',
    incident_escalation_text: 'Safety Desk response within 15 minutes for flagged incidents.',
    dispute_resolution_text: 'Independent dispute arbitration panel review within 48 hours.',
    minimum_age: 18,
    kyc_required: true,
    background_check_required: false,
    consent_required: true,
    public_location_only: true,
    live_location_required: true,
    sos_required: true,
    emergency_contact_required: true,
    chat_moderation_required: true,
    incident_reporting_enabled: true,
    enforcement_type: 'MANUAL_REVIEW',
    exceptions_allowed: true,
    exception_process_text: 'Medical emergency exceptions reviewed by Support Lead.',
    approval_status: 'APPROVED',
    approved_by: 'Disputes Desk',
    versions: [
      { version: 1, effective_from: '2026-01-01T00:00:00.000Z', description: 'Initial Cancellation & Dispute Policy', published_by: 'Finance Team' }
    ]
  }
];

export const DEFAULT_RISK_LEVELS: RiskLevelItem[] = [
  {
    id: 'rk-low',
    code: 'LOW',
    name: 'Low Risk Tier (Score 0-25)',
    description: 'Standard companion bookings during regular hours in verified public places.',
    score_min: 0,
    score_max: 25,
    score: 10,
    color: 'emerald',
    status: 'ACTIVE',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    factors: {
      service_risk: { factor_name: 'Service Risk', weight_score: 10, enabled: true, notes: 'Virtual or public guided tours' },
      duration_risk: { factor_name: 'Duration Risk', weight_score: 10, enabled: true, notes: 'Short sessions < 4 hours' },
      time_risk: { factor_name: 'Time Risk', weight_score: 5, enabled: true, notes: 'Daytime hours (08:00 - 20:00)' },
      location_risk: { factor_name: 'Location Risk', weight_score: 5, enabled: true, notes: 'High traffic verified public places' },
      user_risk: { factor_name: 'User Risk', weight_score: 10, enabled: true, notes: 'Repeat verified client' },
      verification_risk: { factor_name: 'Verification Risk', weight_score: 10, enabled: true, notes: 'Basic Govt ID & OTP verified' },
      booking_risk: { factor_name: 'Booking Risk', weight_score: 5, enabled: true, notes: 'Standard pricing < ₹2,000' }
    },
    required_verification_tier: 'Basic',
    verification_level: 'Basic',
    monitoring_level: 'Standard',
    manual_approval_required: false,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    periodic_checkin_mins: 60,
    maximum_booking_duration: 12,
    escalation_action: 'STANDARD_MONITOR',
    escalation_target_role: 'SAFETY_DESK'
  },
  {
    id: 'rk-med',
    code: 'MEDIUM',
    name: 'Medium Risk Tier (Score 26-50)',
    description: 'Evening events or extended duration sessions requiring periodic check-ins.',
    score_min: 26,
    score_max: 50,
    score: 35,
    color: 'amber',
    status: 'ACTIVE',
    scope_type: 'CATEGORY',
    category_id: 'cat-1',
    category_name: 'Events & Social',
    factors: {
      service_risk: { factor_name: 'Service Risk', weight_score: 25, enabled: true, notes: 'Social escort or party companion' },
      duration_risk: { factor_name: 'Duration Risk', weight_score: 25, enabled: true, notes: 'Duration 4 to 8 hours' },
      time_risk: { factor_name: 'Time Risk', weight_score: 20, enabled: true, notes: 'Late evening hours (20:00 - 23:00)' },
      location_risk: { factor_name: 'Location Risk', weight_score: 20, enabled: true, notes: 'Crowded night venues' },
      user_risk: { factor_name: 'User Risk', weight_score: 25, enabled: true, notes: 'First-time client account' },
      verification_risk: { factor_name: 'Verification Risk', weight_score: 20, enabled: true, notes: 'Standard verification' },
      booking_risk: { factor_name: 'Booking Risk', weight_score: 20, enabled: true, notes: 'Value ₹2,000 - ₹5,000' }
    },
    required_verification_tier: 'Standard',
    verification_level: 'Standard',
    monitoring_level: 'Enhanced',
    manual_approval_required: false,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    periodic_checkin_mins: 30,
    maximum_booking_duration: 8,
    escalation_action: 'EMERGENCY_OPS_ALERT',
    escalation_target_role: 'SAFETY_DESK'
  },
  {
    id: 'rk-high',
    code: 'HIGH',
    name: 'High Risk Tier (Score 51-75)',
    description: 'Night time escorts or high-value bookings requiring PCC background check & admin sign-off.',
    score_min: 51,
    score_max: 75,
    score: 65,
    color: 'orange',
    status: 'ACTIVE',
    scope_type: 'CATEGORY',
    category_id: 'cat-2',
    category_name: 'Travel & Exploration',
    factors: {
      service_risk: { factor_name: 'Service Risk', weight_score: 55, enabled: true, notes: 'Outstation travel companion' },
      duration_risk: { factor_name: 'Duration Risk', weight_score: 60, enabled: true, notes: 'Full-day session > 8 hours' },
      time_risk: { factor_name: 'Time Risk', weight_score: 65, enabled: true, notes: 'Night hours (23:00 - 05:00)' },
      location_risk: { factor_name: 'Location Risk', weight_score: 60, enabled: true, notes: 'Inter-state highway or remote zone' },
      user_risk: { factor_name: 'User Risk', weight_score: 50, enabled: true, notes: 'Unrated client account' },
      verification_risk: { factor_name: 'Verification Risk', weight_score: 55, enabled: true, notes: 'PCC background check pending' },
      booking_risk: { factor_name: 'Booking Risk', weight_score: 60, enabled: true, notes: 'High value > ₹5,000' }
    },
    required_verification_tier: 'Enhanced',
    verification_level: 'Enhanced',
    monitoring_level: 'Continuous',
    manual_approval_required: true,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    periodic_checkin_mins: 15,
    maximum_booking_duration: 6,
    escalation_action: 'IMMEDIATE_ESCALATION',
    escalation_target_role: 'OPS_LEAD'
  },
  {
    id: 'rk-crit',
    code: 'CRITICAL',
    name: 'Critical Risk Tier (Score 76-100)',
    description: 'Maximum security risk requiring strict admin manual sign-off, live audit, & auto-block protocols.',
    score_min: 76,
    score_max: 100,
    score: 90,
    color: 'purple',
    status: 'ACTIVE',
    scope_type: 'SERVICE',
    service_id: 'srv-101',
    service_name: 'VIP Event Escort Companion',
    factors: {
      service_risk: { factor_name: 'Service Risk', weight_score: 85, enabled: true, notes: 'VIP private escort service' },
      duration_risk: { factor_name: 'Duration Risk', weight_score: 80, enabled: true, notes: 'Multi-day overnight booking' },
      time_risk: { factor_name: 'Time Risk', weight_score: 90, enabled: true, notes: 'Midnight & early morning' },
      location_risk: { factor_name: 'Location Risk', weight_score: 85, enabled: true, notes: 'Private non-verified premises' },
      user_risk: { factor_name: 'User Risk', weight_score: 80, enabled: true, notes: 'Flagged client profile' },
      verification_risk: { factor_name: 'Verification Risk', weight_score: 85, enabled: true, notes: 'Restricted 3D liveness required' },
      booking_risk: { factor_name: 'Booking Risk', weight_score: 90, enabled: true, notes: 'Ultra high value > ₹10,000' }
    },
    required_verification_tier: 'Restricted',
    verification_level: 'Restricted',
    monitoring_level: 'RealTime_Audit',
    manual_approval_required: true,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    periodic_checkin_mins: 10,
    maximum_booking_duration: 4,
    escalation_action: 'AUTO_BLOCK',
    escalation_target_role: 'SUPER_ADMIN'
  }
];

export const DEFAULT_VERIFICATION_PROFILES: VerificationProfileItem[] = [
  {
    id: 'vf-basic',
    code: 'VER-BAS-01',
    name: 'Basic Verification Profile',
    profile_tier: 'Basic',
    verification_level: 'Basic',
    description: 'Email, mobile OTP, government ID, and live selfie check',
    status: 'ACTIVE',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    checks: {
      identity: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Aadhaar, Passport, Voter ID' },
      contact: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Phone OTP & Verified Email' },
      face: { enabled: true, required: true, expiry_days: 180, accepted_documents_text: 'Live Camera Selfie' },
      address: { enabled: false, required: false },
      background: { enabled: false, required: false },
      emergency: { enabled: true, required: true, accepted_documents_text: '1 Primary Emergency Contact' },
      additional_documents: { enabled: false, required: false }
    },
    requirements: {
      email: true, mobile: true, government_id: true, selfie: true, face_match: false,
      address: false, background_check: false, emergency_contact: true, additional_document: false, manual_review: false
    },
    applicability_roles: ['CLIENT', 'COMPANION'],
    applicability_trigger: 'ALL_USERS',
    expiry_duration_days: 365,
    re_verification_policy: 'ANNUAL_RENEWAL',
    failure_action: 'BLOCK_BOOKINGS',
    max_retry_attempts: 3,
    manual_review_required: false,
    auto_approval_enabled: true
  },
  {
    id: 'vf-standard',
    code: 'VER-STD-02',
    name: 'Standard Verification Profile',
    profile_tier: 'Standard',
    verification_level: 'Standard',
    description: 'Basic verification + AI biometric face match and current address proof',
    status: 'ACTIVE',
    scope_type: 'CATEGORY',
    category_id: 'cat-1',
    category_name: 'Events & Social',
    checks: {
      identity: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Aadhaar, Driving License, Passport' },
      contact: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Phone OTP & Email Verification' },
      face: { enabled: true, required: true, expiry_days: 180, accepted_documents_text: 'AI Biometric Liveness & Face Match' },
      address: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Utility Bill, Rent Agreement, Passport' },
      background: { enabled: false, required: false },
      emergency: { enabled: true, required: true, accepted_documents_text: '2 Emergency Contacts' },
      additional_documents: { enabled: false, required: false }
    },
    requirements: {
      email: true, mobile: true, government_id: true, selfie: true, face_match: true,
      address: true, background_check: false, emergency_contact: true, additional_document: false, manual_review: false
    },
    applicability_roles: ['COMPANION'],
    applicability_trigger: 'ALL_USERS',
    expiry_duration_days: 365,
    re_verification_policy: 'ANNUAL_RENEWAL',
    failure_action: 'BLOCK_BOOKINGS',
    max_retry_attempts: 3,
    manual_review_required: false,
    auto_approval_enabled: true
  },
  {
    id: 'vf-enhanced',
    code: 'VER-ENH-03',
    name: 'Enhanced Verification Profile',
    profile_tier: 'Enhanced',
    verification_level: 'Enhanced',
    description: 'Standard + police criminal background check and 2 emergency contacts',
    status: 'ACTIVE',
    scope_type: 'CATEGORY',
    category_id: 'cat-2',
    category_name: 'Travel & Exploration',
    checks: {
      identity: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Govt Issued Photo ID & PAN' },
      contact: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Phone OTP & Work Email' },
      face: { enabled: true, required: true, expiry_days: 180, accepted_documents_text: 'Biometric Face Match 95%+ Confidence' },
      address: { enabled: true, required: true, expiry_days: 365, accepted_documents_text: 'Permanent & Current Address Proof' },
      background: { enabled: true, required: true, expiry_days: 180, accepted_documents_text: 'Police Clearance Certificate (PCC)' },
      emergency: { enabled: true, required: true, accepted_documents_text: '2 Primary Emergency Contacts' },
      additional_documents: { enabled: true, required: false, accepted_documents_text: 'Medical Fitness Certificate' }
    },
    requirements: {
      email: true, mobile: true, government_id: true, selfie: true, face_match: true,
      address: true, background_check: true, emergency_contact: true, additional_document: true, manual_review: false
    },
    applicability_roles: ['COMPANION'],
    applicability_trigger: 'HIGH_RISK_BOOKINGS',
    expiry_duration_days: 180,
    re_verification_policy: 'QUARTERLY_RECHECK',
    failure_action: 'AUTO_SUSPEND',
    max_retry_attempts: 2,
    manual_review_required: true,
    auto_approval_enabled: false
  },
  {
    id: 'vf-restricted',
    code: 'VER-RES-04',
    name: 'Restricted Escort Verification Profile',
    profile_tier: 'Restricted',
    verification_level: 'Restricted',
    description: 'Enhanced verification + mandatory manual admin audit queue sign-off',
    status: 'ACTIVE',
    scope_type: 'SERVICE',
    service_id: 'srv-101',
    service_name: 'VIP Event Escort Companion',
    checks: {
      identity: { enabled: true, required: true, expiry_days: 180, accepted_documents_text: 'Passport & Govt Clearance' },
      contact: { enabled: true, required: true, expiry_days: 180, accepted_documents_text: 'Phone OTP & Verified Email' },
      face: { enabled: true, required: true, expiry_days: 90, accepted_documents_text: '3D Face Liveness & Anti-spoof Scan' },
      address: { enabled: true, required: true, expiry_days: 180, accepted_documents_text: 'Verified Residence Proof' },
      background: { enabled: true, required: true, expiry_days: 90, accepted_documents_text: 'Deep Criminal Background & Legal Audit' },
      emergency: { enabled: true, required: true, accepted_documents_text: '2 Verified Primary Contacts + Guardian' },
      additional_documents: { enabled: true, required: true, accepted_documents_text: 'Medical & Character Reference' }
    },
    requirements: {
      email: true, mobile: true, government_id: true, selfie: true, face_match: true,
      address: true, background_check: true, emergency_contact: true, additional_document: true, manual_review: true
    },
    applicability_roles: ['COMPANION'],
    applicability_trigger: 'NIGHT_BOOKINGS',
    expiry_duration_days: 90,
    re_verification_policy: 'POST_INCIDENT_MANDATORY',
    failure_action: 'AUTO_SUSPEND',
    max_retry_attempts: 1,
    manual_review_required: true,
    auto_approval_enabled: false
  }
];

export const DEFAULT_SAFETY_PROFILES: SafetyProfileItem[] = [
  {
    id: 'sf-std-controls',
    code: 'SAF-STD-01',
    name: 'Standard Companion Safety & Trust Profile',
    description: 'Full active safety controls including panic SOS, live GPS tracking, 30-min check-in, and auto-dispatch.',
    status: 'ACTIVE',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    controls: {
      sos: 'REQUIRED',
      emergency_contact: 'REQUIRED',
      live_location: 'REQUIRED',
      periodic_checkin: 'REQUIRED',
      booking_start_checkin: 'REQUIRED',
      booking_end_checkout: 'REQUIRED',
      safe_location_requirement: 'REQUIRED',
      public_place_requirement: 'REQUIRED',
      location_monitoring: 'REQUIRED'
    },
    automation: {
      geofence: 'REQUIRED',
      emergency_notification: 'REQUIRED',
      admin_emergency_escalation: 'REQUIRED',
      incident_reporting: 'REQUIRED',
      chat_monitoring: 'REQUIRED'
    },
    emergency_protocols: {
      sos_dispatch_mode: 'AUTO_POLICE_AND_CONTACTS',
      emergency_escalation_queue: 'SAFETY_DESK',
      incident_response_sla_mins: 5,
      auto_contact_dispatch_delay_seconds: 30,
      response_rules_matrix_text: 'Instant SMS alert to 2 primary contacts, live GPS link broadcast, and emergency desk pop-up.'
    },
    audit_settings: {
      log_all_events: true,
      export_logs_enabled: true,
      retention_days: 90
    }
  },
  {
    id: 'sf-vip-controls',
    code: 'SAF-VIP-02',
    name: 'VIP Escort Maximum Security Safety Profile',
    description: 'Maximum security controls, continuous 10-min check-ins, 3D geofencing, and immediate police escalation hotline.',
    status: 'ACTIVE',
    scope_type: 'SERVICE',
    service_id: 'srv-101',
    service_name: 'VIP Event Escort Companion',
    controls: {
      sos: 'REQUIRED',
      emergency_contact: 'REQUIRED',
      live_location: 'REQUIRED',
      periodic_checkin: 'REQUIRED',
      booking_start_checkin: 'REQUIRED',
      booking_end_checkout: 'REQUIRED',
      safe_location_requirement: 'REQUIRED',
      public_place_requirement: 'REQUIRED',
      location_monitoring: 'REQUIRED'
    },
    automation: {
      geofence: 'REQUIRED',
      emergency_notification: 'REQUIRED',
      admin_emergency_escalation: 'REQUIRED',
      incident_reporting: 'REQUIRED',
      chat_monitoring: 'REQUIRED'
    },
    emergency_protocols: {
      sos_dispatch_mode: 'AUTO_POLICE_AND_CONTACTS',
      emergency_escalation_queue: 'POLICE_HOTLINE',
      incident_response_sla_mins: 2,
      auto_contact_dispatch_delay_seconds: 0,
      response_rules_matrix_text: 'Zero-delay dispatch, direct hotline to local emergency desk, and continuous audio/video incident recording.'
    },
    audit_settings: {
      log_all_events: true,
      export_logs_enabled: true,
      retention_days: 365
    }
  }
];

export const DEFAULT_BOOKING_RULES: BookingRuleItem[] = [
  {
    id: 'bk-std-rule',
    code: 'BKG-STD-01',
    name: 'Standard Booking & Cancellation Policy',
    description: '2h advance notice, 1h-12h session duration, free cancellation > 24h, and tiered refunds.',
    status: 'ACTIVE',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    booking_rules: {
      min_advance_hours: 2,
      max_advance_days: 30,
      instant_booking_allowed: true,
      min_duration_hours: 1,
      max_duration_hours: 12,
      extension_allowed: true,
      max_extension_hours: 4,
      rescheduling_allowed: true,
      reschedule_cutoff_hours: 4,
      companion_approval_required: true,
      admin_approval_required: false
    },
    cancellation_rules: {
      free_cancellation_window_mins: 1440, // 24 hours
      customer_cancellation_allowed: true,
      companion_cancellation_penalty_score: 10,
      companion_reassignment_enabled: true,
      tiers: [
        { hoursBeforeBooking: 24, refundPercentage: 100, cancellationFeePercent: 0 },
        { hoursBeforeBooking: 12, refundPercentage: 75, cancellationFeePercent: 25 },
        { hoursBeforeBooking: 2, refundPercentage: 50, cancellationFeePercent: 50 }
      ],
      no_show_grace_period_mins: 20,
      no_show_fee_percent: 100,
      emergency_cancellation_allowed: true,
      emergency_cancellation_policy_text: 'Full refund for verified medical emergencies or severe weather alerts.'
    },
    refund_rules: {
      refund_schedule: 'THREE_TO_FIVE_DAYS',
      platform_fee_non_refundable: true,
      platform_fee_percent: 5,
      gateway_fee_retention_percent: 2,
      partial_refund_enabled: true,
      partial_refund_formula_text: 'Pro-rata refund for unused hours minus 15% administrative fee.',
      auto_refund_processing: true
    },
    min_advance_hours: 2,
    max_advance_days: 30,
    min_duration_hours: 1,
    max_duration_hours: 12,
    same_day_allowed: true,
    instant_booking_allowed: true,
    companion_approval_required: true
  },
  {
    id: 'bk-vip-rule',
    code: 'BKG-VIP-02',
    name: 'VIP Escort Booking & Strict Cancellation Policy',
    description: 'Requires 4h advance notice, 4h min duration, strict 48h cancellation window, and admin sign-off.',
    status: 'ACTIVE',
    scope_type: 'SERVICE',
    service_id: 'srv-101',
    service_name: 'VIP Event Escort Companion',
    booking_rules: {
      min_advance_hours: 4,
      max_advance_days: 14,
      instant_booking_allowed: false,
      min_duration_hours: 4,
      max_duration_hours: 8,
      extension_allowed: false,
      max_extension_hours: 0,
      rescheduling_allowed: true,
      reschedule_cutoff_hours: 12,
      companion_approval_required: true,
      admin_approval_required: true
    },
    cancellation_rules: {
      free_cancellation_window_mins: 2880, // 48 hours
      customer_cancellation_allowed: true,
      companion_cancellation_penalty_score: 25,
      companion_reassignment_enabled: false,
      tiers: [
        { hoursBeforeBooking: 48, refundPercentage: 100, cancellationFeePercent: 0 },
        { hoursBeforeBooking: 24, refundPercentage: 50, cancellationFeePercent: 50 },
        { hoursBeforeBooking: 6, refundPercentage: 25, cancellationFeePercent: 75 }
      ],
      no_show_grace_period_mins: 15,
      no_show_fee_percent: 100,
      emergency_cancellation_allowed: true,
      emergency_cancellation_policy_text: 'Strict review by Operations Desk.'
    },
    refund_rules: {
      refund_schedule: 'INSTANT_PAYMENT_METHOD',
      platform_fee_non_refundable: true,
      platform_fee_percent: 10,
      gateway_fee_retention_percent: 3,
      partial_refund_enabled: false,
      partial_refund_formula_text: 'No partial refunds for VIP escort sessions.',
      auto_refund_processing: false
    },
    min_advance_hours: 4,
    max_advance_days: 14,
    min_duration_hours: 4,
    max_duration_hours: 8,
    same_day_allowed: false,
    instant_booking_allowed: false,
    companion_approval_required: true
  }
];

export const DEFAULT_ELIGIBILITY_PROFILES: EligibilityProfileItem[] = [
  {
    id: 'eg-bas-profile',
    code: 'ELG-BAS-01',
    name: 'Basic Companion Eligibility Profile',
    tier: 'Basic',
    description: 'Age 18-70, minimum rating 4.0, basic KYC verification required.',
    status: 'ACTIVE',
    scope_type: 'GLOBAL',
    category_name: 'All Categories',
    rules: {
      min_age: 18,
      max_age: 70,
      min_rating: 4.0,
      required_verification_level: 'Basic',
      required_documents: ['GOVERNMENT_ID', 'SELFIE_LIVE', 'EMERGENCY_CONTACT'],
      min_completed_sessions: 0,
      require_good_account_standing: true,
      max_active_strikes_allowed: 2,
      restricted_services_text: 'None'
    },
    evaluator: {
      auto_evaluation_enabled: true,
      manual_override_allowed_roles: ['OPS_LEAD', 'SUPER_ADMIN'],
      re_evaluation_interval_days: 90
    },
    minimum_age: 18,
    maximum_age: 70,
    minimum_rating: 4.0,
    minimum_bookings_done: 0
  },
  {
    id: 'eg-std-profile',
    code: 'ELG-STD-02',
    name: 'Standard Social Companion Eligibility Profile',
    tier: 'Standard',
    description: 'Age 21-65, rating 4.3+, standard verification & 5 completed sessions.',
    status: 'ACTIVE',
    scope_type: 'CATEGORY',
    category_id: 'cat-1',
    category_name: 'Events & Social',
    rules: {
      min_age: 21,
      max_age: 65,
      min_rating: 4.3,
      required_verification_level: 'Standard',
      required_documents: ['GOVERNMENT_ID', 'SELFIE_MATCH', 'ADDRESS_PROOF'],
      min_completed_sessions: 5,
      require_good_account_standing: true,
      max_active_strikes_allowed: 1,
      restricted_services_text: 'Restricted for unverified late-night events.'
    },
    evaluator: {
      auto_evaluation_enabled: true,
      manual_override_allowed_roles: ['OPS_LEAD', 'SUPER_ADMIN'],
      re_evaluation_interval_days: 60
    },
    minimum_age: 21,
    maximum_age: 65,
    minimum_rating: 4.3,
    minimum_bookings_done: 5
  },
  {
    id: 'eg-vip-profile',
    code: 'ELG-RES-04',
    name: 'Restricted VIP Escort Companion Eligibility Profile',
    tier: 'Restricted',
    description: 'Age 21-50, rating 4.8+, police background PCC check, 20+ completed sessions, and mandatory admin review.',
    status: 'ACTIVE',
    scope_type: 'SERVICE',
    service_id: 'srv-101',
    service_name: 'VIP Event Escort Companion',
    rules: {
      min_age: 21,
      max_age: 50,
      min_rating: 4.8,
      required_verification_level: 'Restricted',
      required_documents: ['GOVERNMENT_ID', 'PCC_POLICE_CLEARANCE', 'MEDICAL_CERTIFICATE', 'INTERVIEW_SIGN_OFF'],
      min_completed_sessions: 20,
      require_good_account_standing: true,
      max_active_strikes_allowed: 0,
      restricted_services_text: 'Requires high-security ops desk manual sign-off.'
    },
    evaluator: {
      auto_evaluation_enabled: false,
      manual_override_allowed_roles: ['SUPER_ADMIN'],
      re_evaluation_interval_days: 30
    },
    minimum_age: 21,
    maximum_age: 50,
    minimum_rating: 4.8,
    minimum_bookings_done: 20
  }
];

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-1',
    code: 'CAT-EVT-01',
    name: 'Events & Social',
    slug: 'events-social',
    short_description: 'Corporate galas, weddings, networking expos & social gatherings',
    description: 'Professional companion support for formal events, award ceremonies, and family celebrations.',
    icon: 'Users',
    banner_image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    display_order: 1,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-event-pro',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-2',
    name: 'Travel & Exploration',
    slug: 'travel-exploration',
    short_description: 'Local city guides, road trips, food crawls & sightseeing',
    description: 'Explore new cities safely with trusted local guides, translators, and travel buddies.',
    icon: 'Compass',
    banner_image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
    display_order: 2,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-med',
    default_verification_profile_id: 'vf-enhanced',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-3',
    name: 'Care & Assistance',
    slug: 'care-assistance',
    short_description: 'Compassionate assistance for senior citizens & medical visits',
    description: 'Gentle companionship, hospital navigation, grocery errands, and elderly support (Companionship/Assistance only, strictly no medical treatment/advice).',
    icon: 'Heart',
    banner_image: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80',
    display_order: 3,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 25,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-enhanced',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-4',
    name: 'Study, Career & Work',
    slug: 'study-career-work',
    short_description: 'Productivity partner, library buddy & cafe co-working',
    description: 'Stay focused with accountability companions for exam prep, brainstorming, and remote work.',
    icon: 'BookOpen',
    banner_image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
    display_order: 4,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-5',
    name: 'Fitness, Sports & Outdoor',
    slug: 'fitness-sports-outdoor',
    short_description: 'Workout spotting, running, cycling & sports partner',
    description: 'Jogging pacing buddies, gym weightlifting spotters, tennis partners, and trail hikers.',
    icon: 'Activity',
    banner_image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    display_order: 5,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 20,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-med',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-6',
    name: 'Gaming & Entertainment',
    slug: 'gaming-entertainment',
    short_description: 'Co-op gaming, esports, movie companions & Discord voice',
    description: 'Online gaming partners for ranked FPS, RPG co-op play, and movie viewing companions.',
    icon: 'Gamepad',
    banner_image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    display_order: 6,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-7',
    name: 'Social & Lifestyle',
    slug: 'social-lifestyle',
    short_description: 'Coffee conversations, dining partners & shopping assistance',
    description: 'Polite conversation partners for dining out, coffee breaks, and shopping trips.',
    icon: 'Coffee',
    banner_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    display_order: 7,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-8',
    name: 'Pets & Hobbies',
    slug: 'pets-hobbies',
    short_description: 'Dog walking, photography companion, art & crafting buddy',
    description: 'Enthusiastic companions for pet walks, photography expeditions, and creative hobbies.',
    icon: 'Dog',
    banner_image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
    display_order: 8,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-9',
    name: 'Technology & Digital',
    slug: 'technology-digital',
    short_description: 'Tech setup support, digital literacy & gadget tutoring',
    description: 'Help with smart device setup, smartphone learning, and tech troubleshooting.',
    icon: 'Laptop',
    banner_image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    display_order: 9,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-10',
    name: 'Wellness & Mindfulness',
    slug: 'wellness-mindfulness',
    short_description: 'Meditation partner, nature walk companion & relaxation',
    description: 'Peaceful companions for yoga sessions, park meditation, and stress-free walks.',
    icon: 'Sun',
    banner_image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&auto=format&fit=crop&q=80',
    display_order: 10,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 20,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-11',
    name: 'Home & Personal Assistance',
    slug: 'home-personal-assistance',
    short_description: 'Errand assistance, home organizing & queue standing',
    description: 'Help with daily life tasks, administrative queues, home organizing, and personal task execution.',
    icon: 'Home',
    banner_image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    display_order: 11,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-12',
    name: 'Community & Volunteering',
    slug: 'community-volunteering',
    short_description: 'Social causes, beach cleanups & shelter volunteering',
    description: 'Join community outreach projects, animal rescue events, and environmental cleanups.',
    icon: 'Globe',
    banner_image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&auto=format&fit=crop&q=80',
    display_order: 12,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  }
];

// Helper to generate service items
function createSrv(
  id: string,
  catId: string,
  catName: string,
  name: string,
  desc: string,
  order: number,
  isFeatured = false,
  pricingId = 'pr-hourly-std',
  riskId = 'rk-low'
): ServiceItem {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  return {
    id,
    category_id: catId,
    category_name: catName,
    name,
    slug,
    short_description: desc,
    description: `${name} — Professional companion support and assistance under full escrow and safety protection.`,
    icon: 'Sparkles',
    display_order: order,
    status: 'PUBLISHED',
    is_featured: isFeatured,
    minimum_age: 18,
    maximum_age: 75,
    online_allowed: true,
    offline_allowed: true,
    location_required: true,
    duration_required: true,
    risk_level_id: riskId,
    pricing_profile_id: pricingId,
    rules_profile_id: 'rl-std-safety',
    policy_id: 'pol-std-v1',
    verification_profile_id: 'vf-standard',
    safety_profile_id: 'sf-std-controls',
    booking_rule_id: 'bk-std-rule',
    eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-10T00:00:00.000Z',
    updated_at: '2026-01-10T00:00:00.000Z'
  };
}

export const INITIAL_SERVICES: ServiceItem[] = [
  // 1. Events & Social (cat-1)
  createSrv('srv-101', 'cat-1', 'Events & Social', 'Event Companion', 'General event companion for social functions and galas', 1, true, 'pr-event-pro'),
  createSrv('srv-102', 'cat-1', 'Events & Social', 'Wedding Companion', 'Friendly, well-groomed guest for family weddings', 2, true, 'pr-event-pro'),
  createSrv('srv-103', 'cat-1', 'Events & Social', 'Party Companion', 'Lively companion for private parties and celebrations', 3, false, 'pr-hourly-std'),
  createSrv('srv-104', 'cat-1', 'Events & Social', 'Birthday/Celebration Companion', 'Celebration partner for birthdays and anniversaries', 4, false, 'pr-hourly-std'),
  createSrv('srv-105', 'cat-1', 'Events & Social', 'Corporate Event Companion', 'Professional presence at business summits and dinners', 5, true, 'pr-event-pro'),
  createSrv('srv-106', 'cat-1', 'Events & Social', 'Conference Companion', 'Companion for multi-day conventions and expos', 6, false, 'pr-event-pro'),
  createSrv('srv-107', 'cat-1', 'Events & Social', 'Exhibition Companion', 'Art, tech, and trade fair exhibition companion', 7, false, 'pr-hourly-std'),
  createSrv('srv-108', 'cat-1', 'Events & Social', 'Cultural Event Companion', 'Companion for theater, dance, and heritage programs', 8, false, 'pr-hourly-std'),
  createSrv('srv-109', 'cat-1', 'Events & Social', 'Festival Companion', 'Music and cultural festival companion', 9, false, 'pr-hourly-std'),
  createSrv('srv-110', 'cat-1', 'Events & Social', 'Networking Event Companion', 'Business networking assistant and intro buddy', 10, false, 'pr-hourly-std'),
  createSrv('srv-111', 'cat-1', 'Events & Social', 'Award/Business Event Companion', 'Formal companion for award ceremonies and galas', 11, false, 'pr-event-pro'),

  // 2. Travel & Exploration (cat-2)
  createSrv('srv-201', 'cat-2', 'Travel & Exploration', 'Travel Companion', 'Long distance and city travel buddy', 1, true, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-202', 'cat-2', 'Travel & Exploration', 'City Guide', 'Local expert city walking guide', 2, true, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-203', 'cat-2', 'Travel & Exploration', 'Local Experience', 'Curated local hidden gems and neighborhood tours', 3, false, 'pr-hourly-std'),
  createSrv('srv-204', 'cat-2', 'Travel & Exploration', 'Sightseeing Companion', 'Monument, museum, and park tour guide', 4, false, 'pr-hourly-std'),
  createSrv('srv-205', 'cat-2', 'Travel & Exploration', 'Road Trip Companion', 'Outstation driving and highway travel buddy', 5, true, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-206', 'cat-2', 'Travel & Exploration', 'Shopping Tour', 'Bazaar, handicraft, and mall shopping guide', 6, false, 'pr-hourly-std'),
  createSrv('srv-207', 'cat-2', 'Travel & Exploration', 'Food Tour', 'Street food crawl and culinary tasting guide', 7, false, 'pr-hourly-std'),
  createSrv('srv-208', 'cat-2', 'Travel & Exploration', 'Tourist Assistance', 'Navigation, language translation, and currency guidance', 8, false, 'pr-hourly-std'),
  createSrv('srv-209', 'cat-2', 'Travel & Exploration', 'Public Transport Assistance', 'Metro, bus, and local train navigation escort', 9, false, 'pr-fixed-budget'),
  createSrv('srv-210', 'cat-2', 'Travel & Exploration', 'Airport Assistance', 'Terminal check-in, luggage, and gate escort', 10, false, 'pr-hourly-std'),
  createSrv('srv-211', 'cat-2', 'Travel & Exploration', 'Train/Bus Travel Companion', 'Railway station escort and train journey companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-212', 'cat-2', 'Travel & Exploration', 'Photography Tour Companion', 'Camera helper and photo shoot location guide', 12, false, 'pr-hourly-std'),
  createSrv('srv-213', 'cat-2', 'Travel & Exploration', 'Adventure Trip Companion', 'Camping, kayaking, and outdoor excursion buddy', 13, false, 'pr-hourly-std', 'rk-med'),

  // 3. Care & Assistance (cat-3) (Companionship/Assistance only, strictly no medical treatment/advice)
  createSrv('srv-301', 'cat-3', 'Care & Assistance', 'Elderly Companion', 'Friendly conversation and companionship for seniors', 1, true, 'pr-hourly-std'),
  createSrv('srv-302', 'cat-3', 'Care & Assistance', 'Hospital Companion', 'Non-medical escort for hospital waiting rooms and registrations', 2, true, 'pr-hourly-std'),
  createSrv('srv-303', 'cat-3', 'Care & Assistance', 'Doctor Appointment Companion', 'Navigation and waiting room companion for clinic visits', 3, false, 'pr-hourly-std'),
  createSrv('srv-304', 'cat-3', 'Care & Assistance', 'Medical Appointment Escort', 'Safe accompaniment to scheduled health checkups', 4, false, 'pr-hourly-std'),
  createSrv('srv-305', 'cat-3', 'Care & Assistance', 'Pharmacy Visit Assistance', 'Accompaniment to chemist shops to fetch prescriptions', 5, false, 'pr-fixed-budget'),
  createSrv('srv-306', 'cat-3', 'Care & Assistance', 'Grocery Assistance', 'Shopping escort for vegetables and household items', 6, false, 'pr-fixed-budget'),
  createSrv('srv-307', 'cat-3', 'Care & Assistance', 'Daily Errand Assistance', 'Help with day-to-day outside tasks', 7, false, 'pr-fixed-budget'),
  createSrv('srv-308', 'cat-3', 'Care & Assistance', 'Accessibility Assistance', 'Walking and wheelchair assistance in public venues', 8, false, 'pr-hourly-std'),
  createSrv('srv-309', 'cat-3', 'Care & Assistance', 'Walking Companion', 'Gentle morning/evening park walking buddy', 9, false, 'pr-fixed-budget'),
  createSrv('srv-310', 'cat-3', 'Care & Assistance', 'Reading/Conversation for Elderly', 'Book reading, newspaper summary, and storytelling', 10, false, 'pr-fixed-budget'),
  createSrv('srv-311', 'cat-3', 'Care & Assistance', 'Hospital Discharge Assistance', 'Taxi hailing and luggage help upon hospital exit', 11, false, 'pr-hourly-std'),
  createSrv('srv-312', 'cat-3', 'Care & Assistance', 'Government/Office Visit Assistance', 'Escort for senior citizens visiting administrative offices', 12, false, 'pr-hourly-std'),

  // 4. Study, Career & Work (cat-4)
  createSrv('srv-401', 'cat-4', 'Study, Career & Work', 'Study Buddy', 'Focus and accountability partner for studies', 1, false, 'pr-fixed-budget'),
  createSrv('srv-402', 'cat-4', 'Study, Career & Work', 'Library Companion', 'Silent study partner in libraries', 2, false, 'pr-fixed-budget'),
  createSrv('srv-403', 'cat-4', 'Study, Career & Work', 'Co-working Buddy', 'Cafe and co-working space laptop work companion', 3, true, 'pr-fixed-budget'),
  createSrv('srv-404', 'cat-4', 'Study, Career & Work', 'Online Study Partner', 'Virtual study room timer and goal checker', 4, false, 'pr-fixed-budget'),
  createSrv('srv-405', 'cat-4', 'Study, Career & Work', 'Exam Preparation Buddy', 'Mock test timer and flashcard partner', 5, false, 'pr-fixed-budget'),
  createSrv('srv-406', 'cat-4', 'Study, Career & Work', 'Interview Practice Buddy', 'Mock job interview practice partner', 6, false, 'pr-hourly-std'),
  createSrv('srv-407', 'cat-4', 'Study, Career & Work', 'Career Discussion', 'Peer feedback on job paths and goals', 7, false, 'pr-hourly-std'),
  createSrv('srv-408', 'cat-4', 'Study, Career & Work', 'Resume Discussion', 'CV formatting and feedback discussion', 8, false, 'pr-fixed-budget'),
  createSrv('srv-409', 'cat-4', 'Study, Career & Work', 'Professional Networking', 'Business expo networking companion', 9, false, 'pr-hourly-std'),
  createSrv('srv-410', 'cat-4', 'Study, Career & Work', 'Conference/Business Meeting Companion', 'Professional presence at business meets', 10, false, 'pr-event-pro'),
  createSrv('srv-411', 'cat-4', 'Study, Career & Work', 'Project Discussion Buddy', 'Brainstorming and project planning partner', 11, false, 'pr-hourly-std'),
  createSrv('srv-412', 'cat-4', 'Study, Career & Work', 'Skill Practice Partner', 'Coding, language, or public speaking practice', 12, false, 'pr-fixed-budget'),

  // 5. Fitness, Sports & Outdoor (cat-5)
  createSrv('srv-501', 'cat-5', 'Fitness, Sports & Outdoor', 'Walking Buddy', 'Regular morning/evening brisk walk partner', 1, false, 'pr-fixed-budget'),
  createSrv('srv-502', 'cat-5', 'Fitness, Sports & Outdoor', 'Running Partner', '5K/10K marathon pacing partner', 2, false, 'pr-hourly-std'),
  createSrv('srv-503', 'cat-5', 'Fitness, Sports & Outdoor', 'Jogging Partner', 'Park jogging and cardio partner', 3, false, 'pr-fixed-budget'),
  createSrv('srv-504', 'cat-5', 'Fitness, Sports & Outdoor', 'Cycling Partner', 'City and highway cycling buddy', 4, false, 'pr-hourly-std'),
  createSrv('srv-505', 'cat-5', 'Fitness, Sports & Outdoor', 'Gym Buddy', 'Weightlifting spotter and workout partner', 5, true, 'pr-hourly-std'),
  createSrv('srv-506', 'cat-5', 'Fitness, Sports & Outdoor', 'Yoga Partner', 'Park or studio yoga session buddy', 6, false, 'pr-fixed-budget'),
  createSrv('srv-507', 'cat-5', 'Fitness, Sports & Outdoor', 'Badminton Partner', 'Racket court opponent and sparring partner', 7, true, 'pr-hourly-std'),
  createSrv('srv-508', 'cat-5', 'Fitness, Sports & Outdoor', 'Cricket Partner', 'Turf cricket box match player', 8, false, 'pr-hourly-std'),
  createSrv('srv-509', 'cat-5', 'Fitness, Sports & Outdoor', 'Football Partner', '5-a-side turf football player', 9, false, 'pr-hourly-std'),
  createSrv('srv-510', 'cat-5', 'Fitness, Sports & Outdoor', 'Basketball Partner', 'Court pickup game player', 10, false, 'pr-hourly-std'),
  createSrv('srv-511', 'cat-5', 'Fitness, Sports & Outdoor', 'Swimming Companion', 'Pool lap swimming buddy', 11, false, 'pr-hourly-std'),
  createSrv('srv-512', 'cat-5', 'Fitness, Sports & Outdoor', 'Hiking Partner', 'Day trail hiking buddy', 12, false, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-513', 'cat-5', 'Fitness, Sports & Outdoor', 'Trekking Companion', 'Mountain and hill trek companion', 13, false, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-514', 'cat-5', 'Fitness, Sports & Outdoor', 'Outdoor Activity Partner', 'Frisbee, obstacle course, or park games', 14, false, 'pr-hourly-std'),

  // 6. Gaming & Entertainment (cat-6)
  createSrv('srv-601', 'cat-6', 'Gaming & Entertainment', 'Gaming Buddy', 'Console and PC co-op gaming partner', 1, true, 'pr-fixed-budget'),
  createSrv('srv-602', 'cat-6', 'Gaming & Entertainment', 'Multiplayer Gaming', 'Online duo queue partner (Valorant, BGMI, GTA)', 2, false, 'pr-fixed-budget'),
  createSrv('srv-603', 'cat-6', 'Gaming & Entertainment', 'Esports Partner', 'Competitive ranked gaming teammate', 3, false, 'pr-fixed-budget'),
  createSrv('srv-604', 'cat-6', 'Gaming & Entertainment', 'Esports Practice', 'Scrims and aim practice partner', 4, false, 'pr-fixed-budget'),
  createSrv('srv-605', 'cat-6', 'Gaming & Entertainment', 'Gaming Event Companion', 'Comic-Con and LAN tournament companion', 5, false, 'pr-hourly-std'),
  createSrv('srv-606', 'cat-6', 'Gaming & Entertainment', 'Movie Companion', 'Cinema theater movie watching buddy', 6, true, 'pr-hourly-std'),
  createSrv('srv-607', 'cat-6', 'Gaming & Entertainment', 'Theatre Companion', 'Stage play and drama audience companion', 7, false, 'pr-hourly-std'),
  createSrv('srv-608', 'cat-6', 'Gaming & Entertainment', 'Concert Companion', 'Live music gig and band concert buddy', 8, true, 'pr-event-pro'),
  createSrv('srv-609', 'cat-6', 'Gaming & Entertainment', 'Music Event Companion', 'Classical, jazz, or EDM night companion', 9, false, 'pr-hourly-std'),
  createSrv('srv-610', 'cat-6', 'Gaming & Entertainment', 'Karaoke Companion', 'Sing-along karaoke bar partner', 10, false, 'pr-hourly-std'),
  createSrv('srv-611', 'cat-6', 'Gaming & Entertainment', 'Live Show Companion', 'Stand-up comedy show companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-612', 'cat-6', 'Gaming & Entertainment', 'Cultural Program Companion', 'Dance and folk show audience buddy', 12, false, 'pr-hourly-std'),

  // 7. Social & Lifestyle (cat-7)
  createSrv('srv-701', 'cat-7', 'Social & Lifestyle', 'Conversation Buddy', 'Engaging, friendly chat companion over coffee', 1, true, 'pr-hourly-std'),
  createSrv('srv-702', 'cat-7', 'Social & Lifestyle', 'Coffee Companion', 'Casual cafe coffee catch-up partner', 2, true, 'pr-hourly-std'),
  createSrv('srv-703', 'cat-7', 'Social & Lifestyle', 'Dining Companion', 'Fine dining and restaurant companion', 3, true, 'pr-hourly-std'),
  createSrv('srv-704', 'cat-7', 'Social & Lifestyle', 'Restaurant Companion', 'Lunch or dinner companion', 4, false, 'pr-hourly-std'),
  createSrv('srv-705', 'cat-7', 'Social & Lifestyle', 'Shopping Companion', 'Apparel and outfit feedback shopping buddy', 5, false, 'pr-hourly-std'),
  createSrv('srv-706', 'cat-7', 'Social & Lifestyle', 'Mall Companion', 'Mall strolling and window shopping companion', 6, false, 'pr-fixed-budget'),
  createSrv('srv-707', 'cat-7', 'Social & Lifestyle', 'Book Discussion', 'Literary chat and book exchange partner', 7, false, 'pr-fixed-budget'),
  createSrv('srv-708', 'cat-7', 'Social & Lifestyle', 'Reading Buddy', 'Quiet cafe or park reading companion', 8, false, 'pr-fixed-budget'),
  createSrv('srv-709', 'cat-7', 'Social & Lifestyle', 'Hobby Partner', 'Sharing common creative or lifestyle interests', 9, false, 'pr-fixed-budget'),
  createSrv('srv-710', 'cat-7', 'Social & Lifestyle', 'Social Meetup', 'Accompaniment to public social meetups', 10, false, 'pr-hourly-std'),
  createSrv('srv-711', 'cat-7', 'Social & Lifestyle', 'Local Social Activity', 'Neighborhood fair and flea market companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-712', 'cat-7', 'Social & Lifestyle', 'Language Practice Partner', 'English, French, or regional language conversation', 12, false, 'pr-hourly-std'),

  // 8. Pets & Hobbies (cat-8)
  createSrv('srv-801', 'cat-8', 'Pets & Hobbies', 'Pet Walking', 'Dog park walking and exercise buddy', 1, true, 'pr-fixed-budget'),
  createSrv('srv-802', 'cat-8', 'Pets & Hobbies', 'Pet Companion', 'Playtime companion for pets', 2, false, 'pr-fixed-budget'),
  createSrv('srv-803', 'cat-8', 'Pets & Hobbies', 'Vet Visit Companion', 'Pet clinic waiting room companion', 3, false, 'pr-hourly-std'),
  createSrv('srv-804', 'cat-8', 'Pets & Hobbies', 'Pet Activity Partner', 'Pet grooming or agility park escort', 4, false, 'pr-fixed-budget'),
  createSrv('srv-805', 'cat-8', 'Pets & Hobbies', 'Photography Companion', 'Outdoor camera helper and lighting buddy', 5, false, 'pr-hourly-std'),
  createSrv('srv-806', 'cat-8', 'Pets & Hobbies', 'Photography Walk', 'Street photography and heritage walk buddy', 6, false, 'pr-hourly-std'),
  createSrv('srv-807', 'cat-8', 'Pets & Hobbies', 'Art Partner', 'Gallery visit or museum sketching buddy', 7, false, 'pr-fixed-budget'),
  createSrv('srv-808', 'cat-8', 'Pets & Hobbies', 'Drawing Partner', 'Pencil, watercolor, or digital art partner', 8, false, 'pr-fixed-budget'),
  createSrv('srv-809', 'cat-8', 'Pets & Hobbies', 'Music Practice Partner', 'Vocal or instrumental jam practice buddy', 9, false, 'pr-hourly-std'),
  createSrv('srv-810', 'cat-8', 'Pets & Hobbies', 'Instrument Practice Partner', 'Guitar, keyboard, or violin duet partner', 10, false, 'pr-hourly-std'),
  createSrv('srv-811', 'cat-8', 'Pets & Hobbies', 'Cooking Hobby Partner', 'Baking or recipe testing companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-812', 'cat-8', 'Pets & Hobbies', 'Gardening Partner', 'Plant nursery visit and potting buddy', 12, false, 'pr-fixed-budget'),
  createSrv('srv-813', 'cat-8', 'Pets & Hobbies', 'Craft Partner', 'DIY, pottery, or knitting companion', 13, false, 'pr-fixed-budget'),

  // 9. Technology & Digital (cat-9)
  createSrv('srv-901', 'cat-9', 'Technology & Digital', 'Smartphone Assistance', 'Helping learn smartphone settings, camera, & apps', 1, true, 'pr-fixed-budget'),
  createSrv('srv-902', 'cat-9', 'Technology & Digital', 'Computer Assistance', 'Basic laptop software guidance & typing', 2, false, 'pr-fixed-budget'),
  createSrv('srv-903', 'cat-9', 'Technology & Digital', 'Basic Digital Help', 'General tech setup and troubleshooting help', 3, false, 'pr-fixed-budget'),
  createSrv('srv-904', 'cat-9', 'Technology & Digital', 'Online Form Assistance', 'Guiding through online applications & forms', 4, false, 'pr-fixed-budget'),
  createSrv('srv-905', 'cat-9', 'Technology & Digital', 'Digital Service Assistance', 'Online services setup and usage guide', 5, false, 'pr-fixed-budget'),
  createSrv('srv-906', 'cat-9', 'Technology & Digital', 'App/Website Guidance', 'Teaching how to navigate specific mobile apps', 6, false, 'pr-fixed-budget'),
  createSrv('srv-907', 'cat-9', 'Technology & Digital', 'Video Call Assistance', 'Setting up Zoom/WhatsApp video calls for family', 7, false, 'pr-fixed-budget'),
  createSrv('srv-908', 'cat-9', 'Technology & Digital', 'Digital Payment Guidance', 'Teaching safe UPI and NetBanking practices', 8, true, 'pr-fixed-budget'),
  createSrv('srv-909', 'cat-9', 'Technology & Digital', 'Online Booking Assistance', 'Helping book train tickets, cabs, or hotel stays', 9, false, 'pr-fixed-budget'),
  createSrv('srv-910', 'cat-9', 'Technology & Digital', 'Basic Tech Learning', 'Step-by-step digital literacy companion', 10, false, 'pr-fixed-budget'),

  // 10. Wellness & Mindfulness (cat-10)
  createSrv('srv-1001', 'cat-10', 'Wellness & Mindfulness', 'Meditation Buddy', 'Silent park or studio meditation companion', 1, true, 'pr-hourly-std'),
  createSrv('srv-1002', 'cat-10', 'Wellness & Mindfulness', 'Yoga Buddy', 'Hatha/Vinyasa yoga practice partner', 2, false, 'pr-hourly-std'),
  createSrv('srv-1003', 'cat-10', 'Wellness & Mindfulness', 'Nature Walk', 'Calming forest or botanical garden walk', 3, true, 'pr-fixed-budget'),
  createSrv('srv-1004', 'cat-10', 'Wellness & Mindfulness', 'Mindfulness Partner', 'Mindful listening and presence partner', 4, false, 'pr-hourly-std'),
  createSrv('srv-1005', 'cat-10', 'Wellness & Mindfulness', 'Relaxation Companion', 'Peaceful, low-stress park relaxation buddy', 5, false, 'pr-fixed-budget'),
  createSrv('srv-1006', 'cat-10', 'Wellness & Mindfulness', 'Breathing Practice Partner', 'Pranayama and deep breathing practice partner', 6, false, 'pr-fixed-budget'),
  createSrv('srv-1007', 'cat-10', 'Wellness & Mindfulness', 'Wellness Activity Partner', 'Sound bath or wellness retreat companion', 7, false, 'pr-hourly-std'),
  createSrv('srv-1008', 'cat-10', 'Wellness & Mindfulness', 'Healthy Lifestyle Buddy', 'Organic market and healthy habit partner', 8, false, 'pr-fixed-budget'),
  createSrv('srv-1009', 'cat-10', 'Wellness & Mindfulness', 'Outdoor Relaxation', 'Sunset or lakeside quiet companion', 9, false, 'pr-fixed-budget'),
  createSrv('srv-1010', 'cat-10', 'Wellness & Mindfulness', 'Personal Development Discussion', 'Goal setting and self-improvement chat', 10, false, 'pr-hourly-std'),

  // 11. Home & Personal Assistance (cat-11)
  createSrv('srv-1101', 'cat-11', 'Home & Personal Assistance', 'Home Errand Companion', 'Helper for home tasks and outstation errands', 1, true, 'pr-fixed-budget'),
  createSrv('srv-1102', 'cat-11', 'Home & Personal Assistance', 'Grocery Assistance', 'Supermarket and local mandi shopping companion', 2, false, 'pr-fixed-budget'),
  createSrv('srv-1103', 'cat-11', 'Home & Personal Assistance', 'Shopping Assistance', 'General retail and household shopping companion', 3, false, 'pr-fixed-budget'),
  createSrv('srv-1104', 'cat-11', 'Home & Personal Assistance', 'Bank/Post Office Visit Companion', 'Escort and waiting room buddy for bank visits', 4, false, 'pr-fixed-budget'),
  createSrv('srv-1105', 'cat-11', 'Home & Personal Assistance', 'Government Office Visit Companion', 'Accompaniment to civic offices and passport centers', 5, false, 'pr-hourly-std'),
  createSrv('srv-1106', 'cat-11', 'Home & Personal Assistance', 'Document Submission Assistance', 'Physical document delivery and submission escort', 6, false, 'pr-fixed-budget'),
  createSrv('srv-1107', 'cat-11', 'Home & Personal Assistance', 'Queue/Appointment Assistance', 'Standing in token lines or appointment waiting', 7, true, 'pr-fixed-budget'),
  createSrv('srv-1108', 'cat-11', 'Home & Personal Assistance', 'Moving/Relocation Assistance', 'Accompaniment during packing and house move day', 8, false, 'pr-hourly-std'),
  createSrv('srv-1109', 'cat-11', 'Home & Personal Assistance', 'Furniture/Appliance Shopping Companion', 'Showroom visiting and selection helper', 9, false, 'pr-hourly-std'),
  createSrv('srv-1110', 'cat-11', 'Home & Personal Assistance', 'Home Service Appointment Companion', 'Presence during electrician/plumber repair visits', 10, false, 'pr-fixed-budget'),
  createSrv('srv-1111', 'cat-11', 'Home & Personal Assistance', 'Utility/Service Center Visit', 'Electricity bill/mobile service center visit escort', 11, false, 'pr-fixed-budget'),
  createSrv('srv-1112', 'cat-11', 'Home & Personal Assistance', 'Local Errand Companion', 'Quick neighborhood errands and pickup tasks', 12, false, 'pr-fixed-budget'),

  // 12. Community & Volunteering (cat-12)
  createSrv('srv-1201', 'cat-12', 'Community & Volunteering', 'Community Outreach Companion', 'Social service and community drive companion', 1, true, 'pr-fixed-budget'),
  createSrv('srv-1202', 'cat-12', 'Community & Volunteering', 'Beach/Park Cleanup Buddy', 'Environmental cleanup drive partner', 2, false, 'pr-fixed-budget'),
  createSrv('srv-1203', 'cat-12', 'Community & Volunteering', 'Animal Shelter Volunteer Companion', 'Stray feeding and animal shelter helper', 3, false, 'pr-fixed-budget'),
  createSrv('srv-1204', 'cat-12', 'Community & Volunteering', 'Environmental Cause Partner', 'Tree plantation and green initiative buddy', 4, false, 'pr-fixed-budget'),
  createSrv('srv-1205', 'cat-12', 'Community & Volunteering', 'Charity Event Companion', 'Fundraiser walk and donation drive companion', 5, false, 'pr-fixed-budget'),
  createSrv('srv-1206', 'cat-12', 'Community & Volunteering', 'NGO Activity Partner', 'Volunteer activity partner for local non-profits', 6, false, 'pr-fixed-budget')
];
