import { SosAlertItem, IncidentReport } from './types';

export const INITIAL_SOS_ALERTS: SosAlertItem[] = [
  {
    id: 'sos-101',
    alertRef: 'SOS-2026-8891',
    userId: 'u-102',
    userName: 'Vikram Malhotra',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    userPhone: '+91 98765 43210',
    companionId: 'comp-1',
    companionName: 'Ananya Roy',
    companionPhone: '+91 98111 22334',
    bookingId: 'b-102',
    bookingNumber: 'BK-2026-9042',
    locationName: 'Cyber Hub, Sector 24, Gurugram',
    coordinates: { lat: 28.495, lng: 77.089 },
    severity: 'CRITICAL_EMERGENCY',
    status: 'ACTIVE_DISPATCH',
    triggeredAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    liveAudioFeedActive: true,
    safeWordTriggered: 'BLUE_ORCHID',
    assignedResponder: 'Rapid Response Unit 4 (Gurugram Patrol)',
    notes: 'Companion triggered dynamic safe-word during VIP dinner event. Emergency audio stream active.'
  },
  {
    id: 'sos-102',
    alertRef: 'SOS-2026-7124',
    userId: 'u-105',
    userName: 'Rohan Deshmukh',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    userPhone: '+91 99223 34455',
    companionId: 'comp-4',
    companionName: 'Riya Sen',
    companionPhone: '+91 97788 99001',
    bookingId: 'b-104',
    bookingNumber: 'BK-2026-4412',
    locationName: 'Bandra Kurla Complex (BKC), Mumbai',
    coordinates: { lat: 19.065, lng: 72.868 },
    severity: 'HIGH',
    status: 'RESPONDER_EN_ROUTE',
    triggeredAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    liveAudioFeedActive: false,
    policeDispatchRef: 'MUM-POLICE-9921',
    assignedResponder: 'Sathi Private Guard Patrol #12',
    notes: 'Geofence breach detected. Companion route deviated > 3km from agreed venue perimeter.'
  },
  {
    id: 'sos-103',
    alertRef: 'SOS-2026-3390',
    userId: 'u-108',
    userName: 'Siddharth Nair',
    userAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    userPhone: '+91 95544 33221',
    companionId: 'comp-2',
    companionName: 'Priya Sharma',
    companionPhone: '+91 96655 44332',
    bookingId: 'b-101',
    bookingNumber: 'BK-2026-8821',
    locationName: 'UB City Mall, Bengaluru',
    coordinates: { lat: 12.971, lng: 77.595 },
    severity: 'MEDIUM',
    status: 'RESOLVED_SAFE',
    triggeredAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 105 * 60 * 1000).toISOString(),
    notes: 'Accidental keypress by companion during photo shoot. Confirmed safe via secondary pin verification.'
  }
];

export const INITIAL_INCIDENT_REPORTS: IncidentReport[] = [
  {
    id: 'inc-201',
    incidentRef: 'INC-2026-0041',
    reporterId: 'comp-1',
    reporterName: 'Ananya Roy',
    reporterRole: 'COMPANION',
    targetId: 'u-302',
    targetName: 'Karan Mehra',
    targetRole: 'CUSTOMER',
    bookingId: 'b-209',
    bookingNumber: 'BK-2026-7719',
    category: 'HARASSMENT',
    severity: 'SERIOUS',
    description: 'Client made inappropriate personal demands outside agreed escort category terms during corporate dinner meetup.',
    evidenceUrls: [
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400',
      'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=400'
    ],
    status: 'INVESTIGATING',
    disciplinaryAction: 'ESCROW_FROZEN',
    adminNotes: 'Escrow payment locked pending audio audit review. Client account flagged for risk assessment.',
    filedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString()
  },
  {
    id: 'inc-202',
    incidentRef: 'INC-2026-0038',
    reporterId: 'u-104',
    reporterName: 'Sunil Verma',
    reporterRole: 'CUSTOMER',
    targetId: 'comp-9',
    targetName: 'Meera Kapoor',
    targetRole: 'COMPANION',
    bookingId: 'b-204',
    bookingNumber: 'BK-2026-6612',
    category: 'NO_SHOW_ISOLATION',
    severity: 'MODERATE',
    description: 'Companion arrived 40 minutes late without prior notification and left early.',
    evidenceUrls: [],
    status: 'ACTION_TAKEN',
    disciplinaryAction: 'WARNING_ISSUED',
    adminNotes: 'Warning badge recorded on companion profile. Partial escrow refund issued to customer.',
    filedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  },
  {
    id: 'inc-203',
    incidentRef: 'INC-2026-0012',
    reporterId: 'system',
    reporterName: 'Sathi AI Sentinel Bot',
    reporterRole: 'SYSTEM_AUTOMATION',
    targetId: 'u-991',
    targetName: 'Deepak Saxena',
    targetRole: 'CUSTOMER',
    category: 'IDENTITY_MISMATCH',
    severity: 'CRITICAL',
    description: 'AI Live Selfie Liveness match score below 35%. Document tampering detected during registration.',
    evidenceUrls: ['https://images.unsplash.com/photo-1544717305-2782549b5136?w=400'],
    status: 'RESOLVED',
    disciplinaryAction: 'PERMANENT_BAN',
    adminNotes: 'User permanently blacklisted across Sathi partner network.',
    filedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()
  }
];
