import {
  CategoryItem,
  ServiceItem,
  PricingProfile,
  RulesProfile,
  PolicyItem,
  RiskLevelItem,
  VerificationProfileItem,
  SafetyProfileItem,
  BookingRuleItem,
  EligibilityProfileItem
} from './types/serviceHub';

export const DEFAULT_PRICING_PROFILES: PricingProfile[] = [
  {
    id: 'pr-hourly-std',
    name: 'Standard Hourly Profile',
    pricing_type: 'Hourly',
    base_price: 500,
    currency: 'INR',
    minimum_duration: 1,
    maximum_duration: 12,
    extra_hour_price: 450,
    travel_charge: 100,
    platform_fee: 15,
    companion_commission: 85,
    tax: 18,
    weekend_multiplier: 1.15,
    holiday_multiplier: 1.25,
    surge_enabled: true,
    surge_rules: { peakHoursStart: '18:00', peakHoursEnd: '23:00', surgeMultiplier: 1.2 },
    cancellation_fee: 100,
    no_show_fee: 500,
    status: 'ACTIVE'
  },
  {
    id: 'pr-event-pro',
    name: 'Premium Event Package Profile',
    pricing_type: 'Per Event',
    base_price: 3500,
    currency: 'INR',
    minimum_duration: 4,
    maximum_duration: 10,
    extra_hour_price: 600,
    travel_charge: 250,
    platform_fee: 15,
    companion_commission: 85,
    tax: 18,
    weekend_multiplier: 1.2,
    holiday_multiplier: 1.3,
    surge_enabled: false,
    cancellation_fee: 500,
    no_show_fee: 1500,
    status: 'ACTIVE'
  },
  {
    id: 'pr-fixed-budget',
    name: 'Budget Fixed Profile',
    pricing_type: 'Fixed Price',
    base_price: 350,
    currency: 'INR',
    minimum_duration: 1,
    maximum_duration: 4,
    extra_hour_price: 300,
    travel_charge: 50,
    platform_fee: 10,
    companion_commission: 90,
    tax: 18,
    weekend_multiplier: 1.0,
    holiday_multiplier: 1.1,
    surge_enabled: false,
    cancellation_fee: 50,
    no_show_fee: 200,
    status: 'ACTIVE'
  }
];

export const DEFAULT_RULES_PROFILES: RulesProfile[] = [
  {
    id: 'rl-std-safety',
    name: 'Standard Operational Rules',
    description: 'Basic duration, age, and location verification rules',
    status: 'ACTIVE',
    rules: [
      {
        id: 'r-101',
        name: 'Duration Max Threshold',
        rule_type: 'Duration Rule',
        description: 'Bookings longer than 8 hours require explicit admin approval',
        condition: 'duration_hours',
        operator: 'GREATER_THAN',
        value: 8,
        action: 'REQUIRE_APPROVAL',
        severity: 'MEDIUM',
        status: 'ACTIVE'
      },
      {
        id: 'r-102',
        name: 'Live Location Permission Required',
        rule_type: 'Location Rule',
        description: 'Mandatory live GPS streaming during offline sessions',
        condition: 'live_location_enabled',
        operator: 'EQUALS',
        value: false,
        action: 'BLOCK',
        severity: 'HIGH',
        status: 'ACTIVE'
      }
    ]
  }
];

export const DEFAULT_POLICIES: PolicyItem[] = [
  {
    id: 'pol-std-v1',
    name: 'Standard Companion Policy v1.0',
    description: 'Standard usage policy, public place rules, and mandatory check-in protocol',
    version: 1,
    status: 'PUBLISHED',
    effective_from: '2026-01-01T00:00:00.000Z',
    minimum_age: 18,
    kyc_required: true,
    background_check_required: false,
    emergency_contact_required: true,
    public_location_only: true,
    live_location_required: true,
    sos_required: true,
    chat_moderation_required: true,
    incident_reporting_enabled: true,
    consent_required: true,
    prohibited_activity_text: 'Strictly no illegal activities, private residential meetings without prior verification, or unsafe environments.',
    versions: [
      {
        version: 1,
        effective_from: '2026-01-01T00:00:00.000Z',
        description: 'Initial release of Standard Companion Safety Policy',
        prohibited_activity_text: 'Strictly no illegal activities or private non-verified locations.'
      }
    ]
  }
];

export const DEFAULT_RISK_LEVELS: RiskLevelItem[] = [
  {
    id: 'rk-low',
    name: 'Low Risk',
    code: 'LOW',
    score: 10,
    description: 'Basic verification and safety controls required.',
    color: 'emerald',
    verification_level: 'Basic',
    monitoring_level: 'Standard',
    manual_approval_required: false,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 12,
    status: 'ACTIVE'
  },
  {
    id: 'rk-med',
    name: 'Medium Risk',
    code: 'MEDIUM',
    score: 35,
    description: 'Additional verification and periodic check-in monitoring.',
    color: 'amber',
    verification_level: 'Standard',
    monitoring_level: 'Enhanced',
    manual_approval_required: false,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 8,
    status: 'ACTIVE'
  },
  {
    id: 'rk-high',
    name: 'High Risk',
    code: 'HIGH',
    score: 65,
    description: 'Enhanced background verification and manual admin approval.',
    color: 'rose',
    verification_level: 'Enhanced',
    monitoring_level: 'Strict',
    manual_approval_required: true,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 6,
    status: 'ACTIVE'
  },
  {
    id: 'rk-crit',
    name: 'Critical Risk',
    code: 'CRITICAL',
    score: 90,
    description: 'Restricted service requiring strict admin sign-off and continuous monitoring.',
    color: 'purple',
    verification_level: 'Restricted',
    monitoring_level: 'Continuous',
    manual_approval_required: true,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 4,
    status: 'ACTIVE'
  }
];

export const DEFAULT_VERIFICATION_PROFILES: VerificationProfileItem[] = [
  {
    id: 'vf-basic',
    name: 'Basic Verification Profile',
    description: 'Email, mobile, government ID, and selfie check',
    verification_level: 'Basic',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: false,
      address: false,
      background_check: false,
      emergency_contact: true,
      additional_document: false,
      manual_review: false
    }
  },
  {
    id: 'vf-standard',
    name: 'Standard Verification Profile',
    description: 'Basic verification + face match and address proof',
    verification_level: 'Standard',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: true,
      address: true,
      background_check: false,
      emergency_contact: true,
      additional_document: false,
      manual_review: false
    }
  },
  {
    id: 'vf-enhanced',
    name: 'Enhanced Verification Profile',
    description: 'Standard + background check and additional credentials',
    verification_level: 'Enhanced',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: true,
      address: true,
      background_check: true,
      emergency_contact: true,
      additional_document: true,
      manual_review: false
    }
  },
  {
    id: 'vf-restricted',
    name: 'Restricted Service Verification Profile',
    description: 'Enhanced verification + manual admin review',
    verification_level: 'Restricted',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: true,
      address: true,
      background_check: true,
      emergency_contact: true,
      additional_document: true,
      manual_review: true
    }
  }
];

export const DEFAULT_SAFETY_PROFILES: SafetyProfileItem[] = [
  {
    id: 'sf-std-controls',
    name: 'Standard Safety & Trust Profile',
    description: 'Full active safety suite including SOS, live location, and check-in/out',
    status: 'ACTIVE',
    controls: {
      sos: 'Required',
      emergency_contact: 'Required',
      live_location: 'Required',
      periodic_checkin: 'Required',
      booking_start_checkin: 'Required',
      booking_end_checkout: 'Required',
      geofence: 'Enabled',
      safe_location_requirement: 'Required',
      public_place_requirement: 'Required',
      emergency_notification: 'Enabled',
      admin_emergency_escalation: 'Enabled',
      incident_reporting: 'Enabled',
      chat_monitoring: 'Enabled',
      location_monitoring: 'Required'
    }
  }
];

export const DEFAULT_BOOKING_RULES: BookingRuleItem[] = [
  {
    id: 'bk-std-rule',
    name: 'Standard Booking & Cancellation Policy',
    min_advance_hours: 2,
    max_advance_days: 30,
    min_duration_hours: 1,
    max_duration_hours: 12,
    same_day_allowed: true,
    instant_booking_allowed: true,
    companion_approval_required: true,
    user_approval_required: false,
    cancellation_rules: {
      free_cancellation_window_hours: 24,
      tiers: [
        { hoursBeforeBooking: 24, refundPercentage: 100, cancellationFeePercent: 0 },
        { hoursBeforeBooking: 12, refundPercentage: 75, cancellationFeePercent: 25 },
        { hoursBeforeBooking: 2, refundPercentage: 50, cancellationFeePercent: 50 }
      ],
      no_show_refund_percent: 0
    },
    status: 'ACTIVE'
  }
];

export const DEFAULT_ELIGIBILITY_PROFILES: EligibilityProfileItem[] = [
  {
    id: 'eg-std-profile',
    name: 'Standard Companion Eligibility Profile',
    description: 'Age 18+, rating 4.0+, verified KYC & emergency contact',
    minimum_age: 18,
    maximum_age: 75,
    minimum_rating: 4.0,
    minimum_bookings_done: 0,
    required_documents: ['GOVERNMENT_ID', 'SELFIE_LIVE', 'EMERGENCY_CONTACT'],
    status: 'ACTIVE'
  }
];

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-1',
    name: 'Events & Social',
    slug: 'events-social',
    short_description: 'Corporate galas, weddings, networking expos & social gatherings',
    description: 'Professional companion support for formal events, award ceremonies, and family celebrations.',
    icon: 'Users',
    banner_image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    display_order: 1,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-event-pro',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-2',
    name: 'Travel & Exploration',
    slug: 'travel-exploration',
    short_description: 'Local city guides, road trips, food crawls & sightseeing',
    description: 'Explore new cities safely with trusted local guides, translators, and travel buddies.',
    icon: 'Compass',
    banner_image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
    display_order: 2,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-med',
    default_verification_profile_id: 'vf-enhanced',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-3',
    name: 'Care & Assistance',
    slug: 'care-assistance',
    short_description: 'Compassionate assistance for senior citizens & medical visits',
    description: 'Gentle companionship, hospital navigation, grocery errands, and elderly support (Companionship/Assistance only, strictly no medical treatment/advice).',
    icon: 'Heart',
    banner_image: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80',
    display_order: 3,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 25,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-enhanced',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-4',
    name: 'Study, Career & Work',
    slug: 'study-career-work',
    short_description: 'Productivity partner, library buddy & cafe co-working',
    description: 'Stay focused with accountability companions for exam prep, brainstorming, and remote work.',
    icon: 'BookOpen',
    banner_image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
    display_order: 4,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-5',
    name: 'Fitness, Sports & Outdoor',
    slug: 'fitness-sports-outdoor',
    short_description: 'Workout spotting, running, cycling & sports partner',
    description: 'Jogging pacing buddies, gym weightlifting spotters, tennis partners, and trail hikers.',
    icon: 'Activity',
    banner_image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    display_order: 5,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 20,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-med',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-6',
    name: 'Gaming & Entertainment',
    slug: 'gaming-entertainment',
    short_description: 'Co-op gaming, esports, movie companions & Discord voice',
    description: 'Online gaming partners for ranked FPS, RPG co-op play, and movie viewing companions.',
    icon: 'Gamepad',
    banner_image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    display_order: 6,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-7',
    name: 'Social & Lifestyle',
    slug: 'social-lifestyle',
    short_description: 'Coffee conversations, dining partners & shopping assistance',
    description: 'Polite conversation partners for dining out, coffee breaks, and shopping trips.',
    icon: 'Coffee',
    banner_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    display_order: 7,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-8',
    name: 'Pets & Hobbies',
    slug: 'pets-hobbies',
    short_description: 'Dog walking, photography companion, art & crafting buddy',
    description: 'Enthusiastic companions for pet walks, photography expeditions, and creative hobbies.',
    icon: 'Dog',
    banner_image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
    display_order: 8,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-9',
    name: 'Technology & Digital',
    slug: 'technology-digital',
    short_description: 'Tech setup support, digital literacy & gadget tutoring',
    description: 'Help with smart device setup, smartphone learning, and tech troubleshooting.',
    icon: 'Laptop',
    banner_image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    display_order: 9,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-10',
    name: 'Wellness & Mindfulness',
    slug: 'wellness-mindfulness',
    short_description: 'Meditation partner, nature walk companion & relaxation',
    description: 'Peaceful companions for yoga sessions, park meditation, and stress-free walks.',
    icon: 'Sun',
    banner_image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&auto=format&fit=crop&q=80',
    display_order: 10,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 20,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-11',
    name: 'Home & Personal Assistance',
    slug: 'home-personal-assistance',
    short_description: 'Errand assistance, home organizing & queue standing',
    description: 'Help with daily life tasks, administrative queues, home organizing, and personal task execution.',
    icon: 'Home',
    banner_image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    display_order: 11,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-12',
    name: 'Community & Volunteering',
    slug: 'community-volunteering',
    short_description: 'Social causes, beach cleanups & shelter volunteering',
    description: 'Join community outreach projects, animal rescue events, and environmental cleanups.',
    icon: 'Globe',
    banner_image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&auto=format&fit=crop&q=80',
    display_order: 12,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  }
];

// Helper to generate service items
function createSrv(
  id: string,
  catId: string,
  catName: string,
  name: string,
  desc: string,
  order: number,
  isFeatured = false,
  pricingId = 'pr-hourly-std',
  riskId = 'rk-low'
): ServiceItem {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  return {
    id,
    category_id: catId,
    category_name: catName,
    name,
    slug,
    short_description: desc,
    description: `${name} — Professional companion support and assistance under full escrow and safety protection.`,
    icon: 'Sparkles',
    display_order: order,
    status: 'PUBLISHED',
    is_featured: isFeatured,
    minimum_age: 18,
    maximum_age: 75,
    online_allowed: true,
    offline_allowed: true,
    location_required: true,
    duration_required: true,
    risk_level_id: riskId,
    pricing_profile_id: pricingId,
    rules_profile_id: 'rl-std-safety',
    policy_id: 'pol-std-v1',
    verification_profile_id: 'vf-standard',
    safety_profile_id: 'sf-std-controls',
    booking_rule_id: 'bk-std-rule',
    eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-10T00:00:00.000Z',
    updated_at: '2026-01-10T00:00:00.000Z'
  };
}

export const INITIAL_SERVICES: ServiceItem[] = [
  // 1. Events & Social (cat-1)
  createSrv('srv-101', 'cat-1', 'Events & Social', 'Event Companion', 'General event companion for social functions and galas', 1, true, 'pr-event-pro'),
  createSrv('srv-102', 'cat-1', 'Events & Social', 'Wedding Companion', 'Friendly, well-groomed guest for family weddings', 2, true, 'pr-event-pro'),
  createSrv('srv-103', 'cat-1', 'Events & Social', 'Party Companion', 'Lively companion for private parties and celebrations', 3, false, 'pr-hourly-std'),
  createSrv('srv-104', 'cat-1', 'Events & Social', 'Birthday/Celebration Companion', 'Celebration partner for birthdays and anniversaries', 4, false, 'pr-hourly-std'),
  createSrv('srv-105', 'cat-1', 'Events & Social', 'Corporate Event Companion', 'Professional presence at business summits and dinners', 5, true, 'pr-event-pro'),
  createSrv('srv-106', 'cat-1', 'Events & Social', 'Conference Companion', 'Companion for multi-day conventions and expos', 6, false, 'pr-event-pro'),
  createSrv('srv-107', 'cat-1', 'Events & Social', 'Exhibition Companion', 'Art, tech, and trade fair exhibition companion', 7, false, 'pr-hourly-std'),
  createSrv('srv-108', 'cat-1', 'Events & Social', 'Cultural Event Companion', 'Companion for theater, dance, and heritage programs', 8, false, 'pr-hourly-std'),
  createSrv('srv-109', 'cat-1', 'Events & Social', 'Festival Companion', 'Music and cultural festival companion', 9, false, 'pr-hourly-std'),
  createSrv('srv-110', 'cat-1', 'Events & Social', 'Networking Event Companion', 'Business networking assistant and intro buddy', 10, false, 'pr-hourly-std'),
  createSrv('srv-111', 'cat-1', 'Events & Social', 'Award/Business Event Companion', 'Formal companion for award ceremonies and galas', 11, false, 'pr-event-pro'),

  // 2. Travel & Exploration (cat-2)
  createSrv('srv-201', 'cat-2', 'Travel & Exploration', 'Travel Companion', 'Long distance and city travel buddy', 1, true, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-202', 'cat-2', 'Travel & Exploration', 'City Guide', 'Local expert city walking guide', 2, true, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-203', 'cat-2', 'Travel & Exploration', 'Local Experience', 'Curated local hidden gems and neighborhood tours', 3, false, 'pr-hourly-std'),
  createSrv('srv-204', 'cat-2', 'Travel & Exploration', 'Sightseeing Companion', 'Monument, museum, and park tour guide', 4, false, 'pr-hourly-std'),
  createSrv('srv-205', 'cat-2', 'Travel & Exploration', 'Road Trip Companion', 'Outstation driving and highway travel buddy', 5, true, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-206', 'cat-2', 'Travel & Exploration', 'Shopping Tour', 'Bazaar, handicraft, and mall shopping guide', 6, false, 'pr-hourly-std'),
  createSrv('srv-207', 'cat-2', 'Travel & Exploration', 'Food Tour', 'Street food crawl and culinary tasting guide', 7, false, 'pr-hourly-std'),
  createSrv('srv-208', 'cat-2', 'Travel & Exploration', 'Tourist Assistance', 'Navigation, language translation, and currency guidance', 8, false, 'pr-hourly-std'),
  createSrv('srv-209', 'cat-2', 'Travel & Exploration', 'Public Transport Assistance', 'Metro, bus, and local train navigation escort', 9, false, 'pr-fixed-budget'),
  createSrv('srv-210', 'cat-2', 'Travel & Exploration', 'Airport Assistance', 'Terminal check-in, luggage, and gate escort', 10, false, 'pr-hourly-std'),
  createSrv('srv-211', 'cat-2', 'Travel & Exploration', 'Train/Bus Travel Companion', 'Railway station escort and train journey companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-212', 'cat-2', 'Travel & Exploration', 'Photography Tour Companion', 'Camera helper and photo shoot location guide', 12, false, 'pr-hourly-std'),
  createSrv('srv-213', 'cat-2', 'Travel & Exploration', 'Adventure Trip Companion', 'Camping, kayaking, and outdoor excursion buddy', 13, false, 'pr-hourly-std', 'rk-med'),

  // 3. Care & Assistance (cat-3) (Companionship/Assistance only, strictly no medical treatment/advice)
  createSrv('srv-301', 'cat-3', 'Care & Assistance', 'Elderly Companion', 'Friendly conversation and companionship for seniors', 1, true, 'pr-hourly-std'),
  createSrv('srv-302', 'cat-3', 'Care & Assistance', 'Hospital Companion', 'Non-medical escort for hospital waiting rooms and registrations', 2, true, 'pr-hourly-std'),
  createSrv('srv-303', 'cat-3', 'Care & Assistance', 'Doctor Appointment Companion', 'Navigation and waiting room companion for clinic visits', 3, false, 'pr-hourly-std'),
  createSrv('srv-304', 'cat-3', 'Care & Assistance', 'Medical Appointment Escort', 'Safe accompaniment to scheduled health checkups', 4, false, 'pr-hourly-std'),
  createSrv('srv-305', 'cat-3', 'Care & Assistance', 'Pharmacy Visit Assistance', 'Accompaniment to chemist shops to fetch prescriptions', 5, false, 'pr-fixed-budget'),
  createSrv('srv-306', 'cat-3', 'Care & Assistance', 'Grocery Assistance', 'Shopping escort for vegetables and household items', 6, false, 'pr-fixed-budget'),
  createSrv('srv-307', 'cat-3', 'Care & Assistance', 'Daily Errand Assistance', 'Help with day-to-day outside tasks', 7, false, 'pr-fixed-budget'),
  createSrv('srv-308', 'cat-3', 'Care & Assistance', 'Accessibility Assistance', 'Walking and wheelchair assistance in public venues', 8, false, 'pr-hourly-std'),
  createSrv('srv-309', 'cat-3', 'Care & Assistance', 'Walking Companion', 'Gentle morning/evening park walking buddy', 9, false, 'pr-fixed-budget'),
  createSrv('srv-310', 'cat-3', 'Care & Assistance', 'Reading/Conversation for Elderly', 'Book reading, newspaper summary, and storytelling', 10, false, 'pr-fixed-budget'),
  createSrv('srv-311', 'cat-3', 'Care & Assistance', 'Hospital Discharge Assistance', 'Taxi hailing and luggage help upon hospital exit', 11, false, 'pr-hourly-std'),
  createSrv('srv-312', 'cat-3', 'Care & Assistance', 'Government/Office Visit Assistance', 'Escort for senior citizens visiting administrative offices', 12, false, 'pr-hourly-std'),

  // 4. Study, Career & Work (cat-4)
  createSrv('srv-401', 'cat-4', 'Study, Career & Work', 'Study Buddy', 'Focus and accountability partner for studies', 1, false, 'pr-fixed-budget'),
  createSrv('srv-402', 'cat-4', 'Study, Career & Work', 'Library Companion', 'Silent study partner in libraries', 2, false, 'pr-fixed-budget'),
  createSrv('srv-403', 'cat-4', 'Study, Career & Work', 'Co-working Buddy', 'Cafe and co-working space laptop work companion', 3, true, 'pr-fixed-budget'),
  createSrv('srv-404', 'cat-4', 'Study, Career & Work', 'Online Study Partner', 'Virtual study room timer and goal checker', 4, false, 'pr-fixed-budget'),
  createSrv('srv-405', 'cat-4', 'Study, Career & Work', 'Exam Preparation Buddy', 'Mock test timer and flashcard partner', 5, false, 'pr-fixed-budget'),
  createSrv('srv-406', 'cat-4', 'Study, Career & Work', 'Interview Practice Buddy', 'Mock job interview practice partner', 6, false, 'pr-hourly-std'),
  createSrv('srv-407', 'cat-4', 'Study, Career & Work', 'Career Discussion', 'Peer feedback on job paths and goals', 7, false, 'pr-hourly-std'),
  createSrv('srv-408', 'cat-4', 'Study, Career & Work', 'Resume Discussion', 'CV formatting and feedback discussion', 8, false, 'pr-fixed-budget'),
  createSrv('srv-409', 'cat-4', 'Study, Career & Work', 'Professional Networking', 'Business expo networking companion', 9, false, 'pr-hourly-std'),
  createSrv('srv-410', 'cat-4', 'Study, Career & Work', 'Conference/Business Meeting Companion', 'Professional presence at business meets', 10, false, 'pr-event-pro'),
  createSrv('srv-411', 'cat-4', 'Study, Career & Work', 'Project Discussion Buddy', 'Brainstorming and project planning partner', 11, false, 'pr-hourly-std'),
  createSrv('srv-412', 'cat-4', 'Study, Career & Work', 'Skill Practice Partner', 'Coding, language, or public speaking practice', 12, false, 'pr-fixed-budget'),

  // 5. Fitness, Sports & Outdoor (cat-5)
  createSrv('srv-501', 'cat-5', 'Fitness, Sports & Outdoor', 'Walking Buddy', 'Regular morning/evening brisk walk partner', 1, false, 'pr-fixed-budget'),
  createSrv('srv-502', 'cat-5', 'Fitness, Sports & Outdoor', 'Running Partner', '5K/10K marathon pacing partner', 2, false, 'pr-hourly-std'),
  createSrv('srv-503', 'cat-5', 'Fitness, Sports & Outdoor', 'Jogging Partner', 'Park jogging and cardio partner', 3, false, 'pr-fixed-budget'),
  createSrv('srv-504', 'cat-5', 'Fitness, Sports & Outdoor', 'Cycling Partner', 'City and highway cycling buddy', 4, false, 'pr-hourly-std'),
  createSrv('srv-505', 'cat-5', 'Fitness, Sports & Outdoor', 'Gym Buddy', 'Weightlifting spotter and workout partner', 5, true, 'pr-hourly-std'),
  createSrv('srv-506', 'cat-5', 'Fitness, Sports & Outdoor', 'Yoga Partner', 'Park or studio yoga session buddy', 6, false, 'pr-fixed-budget'),
  createSrv('srv-507', 'cat-5', 'Fitness, Sports & Outdoor', 'Badminton Partner', 'Racket court opponent and sparring partner', 7, true, 'pr-hourly-std'),
  createSrv('srv-508', 'cat-5', 'Fitness, Sports & Outdoor', 'Cricket Partner', 'Turf cricket box match player', 8, false, 'pr-hourly-std'),
  createSrv('srv-509', 'cat-5', 'Fitness, Sports & Outdoor', 'Football Partner', '5-a-side turf football player', 9, false, 'pr-hourly-std'),
  createSrv('srv-510', 'cat-5', 'Fitness, Sports & Outdoor', 'Basketball Partner', 'Court pickup game player', 10, false, 'pr-hourly-std'),
  createSrv('srv-511', 'cat-5', 'Fitness, Sports & Outdoor', 'Swimming Companion', 'Pool lap swimming buddy', 11, false, 'pr-hourly-std'),
  createSrv('srv-512', 'cat-5', 'Fitness, Sports & Outdoor', 'Hiking Partner', 'Day trail hiking buddy', 12, false, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-513', 'cat-5', 'Fitness, Sports & Outdoor', 'Trekking Companion', 'Mountain and hill trek companion', 13, false, 'pr-hourly-std', 'rk-med'),
  createSrv('srv-514', 'cat-5', 'Fitness, Sports & Outdoor', 'Outdoor Activity Partner', 'Frisbee, obstacle course, or park games', 14, false, 'pr-hourly-std'),

  // 6. Gaming & Entertainment (cat-6)
  createSrv('srv-601', 'cat-6', 'Gaming & Entertainment', 'Gaming Buddy', 'Console and PC co-op gaming partner', 1, true, 'pr-fixed-budget'),
  createSrv('srv-602', 'cat-6', 'Gaming & Entertainment', 'Multiplayer Gaming', 'Online duo queue partner (Valorant, BGMI, GTA)', 2, false, 'pr-fixed-budget'),
  createSrv('srv-603', 'cat-6', 'Gaming & Entertainment', 'Esports Partner', 'Competitive ranked gaming teammate', 3, false, 'pr-fixed-budget'),
  createSrv('srv-604', 'cat-6', 'Gaming & Entertainment', 'Esports Practice', 'Scrims and aim practice partner', 4, false, 'pr-fixed-budget'),
  createSrv('srv-605', 'cat-6', 'Gaming & Entertainment', 'Gaming Event Companion', 'Comic-Con and LAN tournament companion', 5, false, 'pr-hourly-std'),
  createSrv('srv-606', 'cat-6', 'Gaming & Entertainment', 'Movie Companion', 'Cinema theater movie watching buddy', 6, true, 'pr-hourly-std'),
  createSrv('srv-607', 'cat-6', 'Gaming & Entertainment', 'Theatre Companion', 'Stage play and drama audience companion', 7, false, 'pr-hourly-std'),
  createSrv('srv-608', 'cat-6', 'Gaming & Entertainment', 'Concert Companion', 'Live music gig and band concert buddy', 8, true, 'pr-event-pro'),
  createSrv('srv-609', 'cat-6', 'Gaming & Entertainment', 'Music Event Companion', 'Classical, jazz, or EDM night companion', 9, false, 'pr-hourly-std'),
  createSrv('srv-610', 'cat-6', 'Gaming & Entertainment', 'Karaoke Companion', 'Sing-along karaoke bar partner', 10, false, 'pr-hourly-std'),
  createSrv('srv-611', 'cat-6', 'Gaming & Entertainment', 'Live Show Companion', 'Stand-up comedy show companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-612', 'cat-6', 'Gaming & Entertainment', 'Cultural Program Companion', 'Dance and folk show audience buddy', 12, false, 'pr-hourly-std'),

  // 7. Social & Lifestyle (cat-7)
  createSrv('srv-701', 'cat-7', 'Social & Lifestyle', 'Conversation Buddy', 'Engaging, friendly chat companion over coffee', 1, true, 'pr-hourly-std'),
  createSrv('srv-702', 'cat-7', 'Social & Lifestyle', 'Coffee Companion', 'Casual cafe coffee catch-up partner', 2, true, 'pr-hourly-std'),
  createSrv('srv-703', 'cat-7', 'Social & Lifestyle', 'Dining Companion', 'Fine dining and restaurant companion', 3, true, 'pr-hourly-std'),
  createSrv('srv-704', 'cat-7', 'Social & Lifestyle', 'Restaurant Companion', 'Lunch or dinner companion', 4, false, 'pr-hourly-std'),
  createSrv('srv-705', 'cat-7', 'Social & Lifestyle', 'Shopping Companion', 'Apparel and outfit feedback shopping buddy', 5, false, 'pr-hourly-std'),
  createSrv('srv-706', 'cat-7', 'Social & Lifestyle', 'Mall Companion', 'Mall strolling and window shopping companion', 6, false, 'pr-fixed-budget'),
  createSrv('srv-707', 'cat-7', 'Social & Lifestyle', 'Book Discussion', 'Literary chat and book exchange partner', 7, false, 'pr-fixed-budget'),
  createSrv('srv-708', 'cat-7', 'Social & Lifestyle', 'Reading Buddy', 'Quiet cafe or park reading companion', 8, false, 'pr-fixed-budget'),
  createSrv('srv-709', 'cat-7', 'Social & Lifestyle', 'Hobby Partner', 'Sharing common creative or lifestyle interests', 9, false, 'pr-fixed-budget'),
  createSrv('srv-710', 'cat-7', 'Social & Lifestyle', 'Social Meetup', 'Accompaniment to public social meetups', 10, false, 'pr-hourly-std'),
  createSrv('srv-711', 'cat-7', 'Social & Lifestyle', 'Local Social Activity', 'Neighborhood fair and flea market companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-712', 'cat-7', 'Social & Lifestyle', 'Language Practice Partner', 'English, French, or regional language conversation', 12, false, 'pr-hourly-std'),

  // 8. Pets & Hobbies (cat-8)
  createSrv('srv-801', 'cat-8', 'Pets & Hobbies', 'Pet Walking', 'Dog park walking and exercise buddy', 1, true, 'pr-fixed-budget'),
  createSrv('srv-802', 'cat-8', 'Pets & Hobbies', 'Pet Companion', 'Playtime companion for pets', 2, false, 'pr-fixed-budget'),
  createSrv('srv-803', 'cat-8', 'Pets & Hobbies', 'Vet Visit Companion', 'Pet clinic waiting room companion', 3, false, 'pr-hourly-std'),
  createSrv('srv-804', 'cat-8', 'Pets & Hobbies', 'Pet Activity Partner', 'Pet grooming or agility park escort', 4, false, 'pr-fixed-budget'),
  createSrv('srv-805', 'cat-8', 'Pets & Hobbies', 'Photography Companion', 'Outdoor camera helper and lighting buddy', 5, false, 'pr-hourly-std'),
  createSrv('srv-806', 'cat-8', 'Pets & Hobbies', 'Photography Walk', 'Street photography and heritage walk buddy', 6, false, 'pr-hourly-std'),
  createSrv('srv-807', 'cat-8', 'Pets & Hobbies', 'Art Partner', 'Gallery visit or museum sketching buddy', 7, false, 'pr-fixed-budget'),
  createSrv('srv-808', 'cat-8', 'Pets & Hobbies', 'Drawing Partner', 'Pencil, watercolor, or digital art partner', 8, false, 'pr-fixed-budget'),
  createSrv('srv-809', 'cat-8', 'Pets & Hobbies', 'Music Practice Partner', 'Vocal or instrumental jam practice buddy', 9, false, 'pr-hourly-std'),
  createSrv('srv-810', 'cat-8', 'Pets & Hobbies', 'Instrument Practice Partner', 'Guitar, keyboard, or violin duet partner', 10, false, 'pr-hourly-std'),
  createSrv('srv-811', 'cat-8', 'Pets & Hobbies', 'Cooking Hobby Partner', 'Baking or recipe testing companion', 11, false, 'pr-hourly-std'),
  createSrv('srv-812', 'cat-8', 'Pets & Hobbies', 'Gardening Partner', 'Plant nursery visit and potting buddy', 12, false, 'pr-fixed-budget'),
  createSrv('srv-813', 'cat-8', 'Pets & Hobbies', 'Craft Partner', 'DIY, pottery, or knitting companion', 13, false, 'pr-fixed-budget'),

  // 9. Technology & Digital (cat-9)
  createSrv('srv-901', 'cat-9', 'Technology & Digital', 'Smartphone Assistance', 'Helping learn smartphone settings, camera, & apps', 1, true, 'pr-fixed-budget'),
  createSrv('srv-902', 'cat-9', 'Technology & Digital', 'Computer Assistance', 'Basic laptop software guidance & typing', 2, false, 'pr-fixed-budget'),
  createSrv('srv-903', 'cat-9', 'Technology & Digital', 'Basic Digital Help', 'General tech setup and troubleshooting help', 3, false, 'pr-fixed-budget'),
  createSrv('srv-904', 'cat-9', 'Technology & Digital', 'Online Form Assistance', 'Guiding through online applications & forms', 4, false, 'pr-fixed-budget'),
  createSrv('srv-905', 'cat-9', 'Technology & Digital', 'Digital Service Assistance', 'Online services setup and usage guide', 5, false, 'pr-fixed-budget'),
  createSrv('srv-906', 'cat-9', 'Technology & Digital', 'App/Website Guidance', 'Teaching how to navigate specific mobile apps', 6, false, 'pr-fixed-budget'),
  createSrv('srv-907', 'cat-9', 'Technology & Digital', 'Video Call Assistance', 'Setting up Zoom/WhatsApp video calls for family', 7, false, 'pr-fixed-budget'),
  createSrv('srv-908', 'cat-9', 'Technology & Digital', 'Digital Payment Guidance', 'Teaching safe UPI and NetBanking practices', 8, true, 'pr-fixed-budget'),
  createSrv('srv-909', 'cat-9', 'Technology & Digital', 'Online Booking Assistance', 'Helping book train tickets, cabs, or hotel stays', 9, false, 'pr-fixed-budget'),
  createSrv('srv-910', 'cat-9', 'Technology & Digital', 'Basic Tech Learning', 'Step-by-step digital literacy companion', 10, false, 'pr-fixed-budget'),

  // 10. Wellness & Mindfulness (cat-10)
  createSrv('srv-1001', 'cat-10', 'Wellness & Mindfulness', 'Meditation Buddy', 'Silent park or studio meditation companion', 1, true, 'pr-hourly-std'),
  createSrv('srv-1002', 'cat-10', 'Wellness & Mindfulness', 'Yoga Buddy', 'Hatha/Vinyasa yoga practice partner', 2, false, 'pr-hourly-std'),
  createSrv('srv-1003', 'cat-10', 'Wellness & Mindfulness', 'Nature Walk', 'Calming forest or botanical garden walk', 3, true, 'pr-fixed-budget'),
  createSrv('srv-1004', 'cat-10', 'Wellness & Mindfulness', 'Mindfulness Partner', 'Mindful listening and presence partner', 4, false, 'pr-hourly-std'),
  createSrv('srv-1005', 'cat-10', 'Wellness & Mindfulness', 'Relaxation Companion', 'Peaceful, low-stress park relaxation buddy', 5, false, 'pr-fixed-budget'),
  createSrv('srv-1006', 'cat-10', 'Wellness & Mindfulness', 'Breathing Practice Partner', 'Pranayama and deep breathing practice partner', 6, false, 'pr-fixed-budget'),
  createSrv('srv-1007', 'cat-10', 'Wellness & Mindfulness', 'Wellness Activity Partner', 'Sound bath or wellness retreat companion', 7, false, 'pr-hourly-std'),
  createSrv('srv-1008', 'cat-10', 'Wellness & Mindfulness', 'Healthy Lifestyle Buddy', 'Organic market and healthy habit partner', 8, false, 'pr-fixed-budget'),
  createSrv('srv-1009', 'cat-10', 'Wellness & Mindfulness', 'Outdoor Relaxation', 'Sunset or lakeside quiet companion', 9, false, 'pr-fixed-budget'),
  createSrv('srv-1010', 'cat-10', 'Wellness & Mindfulness', 'Personal Development Discussion', 'Goal setting and self-improvement chat', 10, false, 'pr-hourly-std'),

  // 11. Home & Personal Assistance (cat-11)
  createSrv('srv-1101', 'cat-11', 'Home & Personal Assistance', 'Home Errand Companion', 'Helper for home tasks and outstation errands', 1, true, 'pr-fixed-budget'),
  createSrv('srv-1102', 'cat-11', 'Home & Personal Assistance', 'Grocery Assistance', 'Supermarket and local mandi shopping companion', 2, false, 'pr-fixed-budget'),
  createSrv('srv-1103', 'cat-11', 'Home & Personal Assistance', 'Shopping Assistance', 'General retail and household shopping companion', 3, false, 'pr-fixed-budget'),
  createSrv('srv-1104', 'cat-11', 'Home & Personal Assistance', 'Bank/Post Office Visit Companion', 'Escort and waiting room buddy for bank visits', 4, false, 'pr-fixed-budget'),
  createSrv('srv-1105', 'cat-11', 'Home & Personal Assistance', 'Government Office Visit Companion', 'Accompaniment to civic offices and passport centers', 5, false, 'pr-hourly-std'),
  createSrv('srv-1106', 'cat-11', 'Home & Personal Assistance', 'Document Submission Assistance', 'Physical document delivery and submission escort', 6, false, 'pr-fixed-budget'),
  createSrv('srv-1107', 'cat-11', 'Home & Personal Assistance', 'Queue/Appointment Assistance', 'Standing in token lines or appointment waiting', 7, true, 'pr-fixed-budget'),
  createSrv('srv-1108', 'cat-11', 'Home & Personal Assistance', 'Moving/Relocation Assistance', 'Accompaniment during packing and house move day', 8, false, 'pr-hourly-std'),
  createSrv('srv-1109', 'cat-11', 'Home & Personal Assistance', 'Furniture/Appliance Shopping Companion', 'Showroom visiting and selection helper', 9, false, 'pr-hourly-std'),
  createSrv('srv-1110', 'cat-11', 'Home & Personal Assistance', 'Home Service Appointment Companion', 'Presence during electrician/plumber repair visits', 10, false, 'pr-fixed-budget'),
  createSrv('srv-1111', 'cat-11', 'Home & Personal Assistance', 'Utility/Service Center Visit', 'Electricity bill/mobile service center visit escort', 11, false, 'pr-fixed-budget'),
  createSrv('srv-1112', 'cat-11', 'Home & Personal Assistance', 'Local Errand Companion', 'Quick neighborhood errands and pickup tasks', 12, false, 'pr-fixed-budget'),

  // 12. Community & Volunteering (cat-12)
  createSrv('srv-1201', 'cat-12', 'Community & Volunteering', 'Community Outreach Companion', 'Social service and community drive companion', 1, true, 'pr-fixed-budget'),
  createSrv('srv-1202', 'cat-12', 'Community & Volunteering', 'Beach/Park Cleanup Buddy', 'Environmental cleanup drive partner', 2, false, 'pr-fixed-budget'),
  createSrv('srv-1203', 'cat-12', 'Community & Volunteering', 'Animal Shelter Volunteer Companion', 'Stray feeding and animal shelter helper', 3, false, 'pr-fixed-budget'),
  createSrv('srv-1204', 'cat-12', 'Community & Volunteering', 'Environmental Cause Partner', 'Tree plantation and green initiative buddy', 4, false, 'pr-fixed-budget'),
  createSrv('srv-1205', 'cat-12', 'Community & Volunteering', 'Charity Event Companion', 'Fundraiser walk and donation drive companion', 5, false, 'pr-fixed-budget'),
  createSrv('srv-1206', 'cat-12', 'Community & Volunteering', 'NGO Activity Partner', 'Volunteer activity partner for local non-profits', 6, false, 'pr-fixed-budget')
];
