import { FinancialTransaction, PayoutRecord, PaymentGatewayConfig } from './types';

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'txn-101',
    transactionRef: 'TXN-2026-8891',
    bookingId: 'book-101',
    bookingNumber: 'SATHI-8801',
    userId: 'usr-101',
    userName: 'Alexander Wright',
    companionId: 'comp-101',
    companionName: 'Sophia Chen',
    type: 'BOOKING_ESCROW_LOCK',
    amount: 360,
    platformFee: 36,
    escrowFee: 10,
    gstTax: 18,
    netPayoutAmount: 296,
    status: 'HELD_IN_ESCROW',
    paymentMethod: 'STRIPE',
    gatewayRef: 'ch_3Mv8s92e9182kL90',
    notes: 'Escrow vault locked for SF VIP Event',
    createdAt: '2026-08-05T14:30:00Z'
  },
  {
    id: 'txn-102',
    transactionRef: 'TXN-2026-8892',
    bookingId: 'book-102',
    bookingNumber: 'SATHI-8802',
    userId: 'usr-102',
    userName: 'Elena Rostova',
    companionId: 'comp-102',
    companionName: 'Marcus Vance',
    type: 'BOOKING_ESCROW_LOCK',
    amount: 540,
    platformFee: 54,
    escrowFee: 15,
    gstTax: 27,
    netPayoutAmount: 444,
    status: 'HELD_IN_ESCROW',
    paymentMethod: 'CREDIT_CARD',
    gatewayRef: 'ch_4Nx9t03f0293mM01',
    notes: 'Dinner & Concert Escrow Lock in NYC',
    createdAt: '2026-08-05T18:15:00Z'
  },
  {
    id: 'txn-103',
    transactionRef: 'TXN-2026-8893',
    bookingId: 'book-103',
    bookingNumber: 'SATHI-8803',
    userId: 'usr-103',
    userName: 'Kenji Takahashi',
    companionId: 'comp-103',
    companionName: 'Aria Montgomery',
    type: 'COMPANION_PAYOUT',
    amount: 450,
    platformFee: 45,
    escrowFee: 0,
    gstTax: 0,
    netPayoutAmount: 405,
    status: 'COMPLETED',
    paymentMethod: 'WALLET',
    gatewayRef: 'payout_K9102s881',
    notes: 'Companion payout released via Sathi Direct Vault',
    createdAt: '2026-08-04T11:00:00Z'
  },
  {
    id: 'txn-104',
    transactionRef: 'TXN-2026-8894',
    bookingId: 'book-104',
    bookingNumber: 'SATHI-8804',
    userId: 'usr-104',
    userName: 'David Miller',
    companionId: 'comp-104',
    companionName: 'Lucas Thorne',
    type: 'CUSTOMER_REFUND',
    amount: 220,
    platformFee: 0,
    escrowFee: 0,
    gstTax: 0,
    netPayoutAmount: 0,
    status: 'REFUNDED',
    paymentMethod: 'RAZORPAY',
    gatewayRef: 'rfnd_R88192k390',
    notes: 'Mutual cancellation prior to 2-hour window',
    createdAt: '2026-08-03T16:45:00Z'
  },
  {
    id: 'txn-105',
    transactionRef: 'TXN-2026-8895',
    userId: 'usr-105',
    userName: 'Sarah Jenkins',
    type: 'WALLET_TOPUP',
    amount: 500,
    platformFee: 0,
    escrowFee: 0,
    gstTax: 0,
    netPayoutAmount: 500,
    status: 'COMPLETED',
    paymentMethod: 'UPI',
    gatewayRef: 'upi_ref_8820192',
    notes: 'Sathi Wallet instant balance top-up',
    createdAt: '2026-08-02T09:20:00Z'
  },
  {
    id: 'txn-106',
    transactionRef: 'TXN-2026-8896',
    bookingId: 'book-105',
    bookingNumber: 'SATHI-8805',
    userId: 'usr-106',
    userName: 'Vikram Mehta',
    companionId: 'comp-105',
    companionName: 'Priya Sharma',
    type: 'PLATFORM_FEE_CREDIT',
    amount: 80,
    platformFee: 80,
    escrowFee: 0,
    gstTax: 12,
    netPayoutAmount: 0,
    status: 'COMPLETED',
    paymentMethod: 'STRIPE',
    gatewayRef: 'ch_99182ks901',
    notes: '10% Sathi platform commission credited to corporate vault',
    createdAt: '2026-08-01T20:10:00Z'
  }
];

export const INITIAL_PAYOUTS: PayoutRecord[] = [
  {
    id: 'po-101',
    payoutRef: 'PO-2026-4401',
    companionId: 'comp-101',
    companionName: 'Sophia Chen',
    companionAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    bankName: 'JPMorgan Chase & Co.',
    accountNumberMasked: '•••• •••• 9812',
    ifscOrRoutingCode: 'CHASUS33',
    amount: 1450,
    status: 'PAID',
    processedAt: '2026-08-04T12:00:00Z',
    transactionRef: 'TXN-2026-8893'
  },
  {
    id: 'po-102',
    payoutRef: 'PO-2026-4402',
    companionId: 'comp-102',
    companionName: 'Marcus Vance',
    companionAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bankName: 'Bank of America',
    accountNumberMasked: '•••• •••• 4410',
    ifscOrRoutingCode: 'BOFAUS6S',
    amount: 980,
    status: 'PROCESSING',
    processedAt: '2026-08-05T17:30:00Z'
  },
  {
    id: 'po-103',
    payoutRef: 'PO-2026-4403',
    companionId: 'comp-105',
    companionName: 'Priya Sharma',
    companionAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    bankName: 'HDFC Bank Ltd.',
    accountNumberMasked: '•••• •••• 7120',
    ifscOrRoutingCode: 'HDFC0000128',
    amount: 620,
    status: 'PAID',
    processedAt: '2026-08-02T15:10:00Z'
  }
];

export const INITIAL_GATEWAYS: PaymentGatewayConfig[] = [
  {
    id: 'gw-stripe',
    provider: 'STRIPE',
    name: 'Stripe International Gateway',
    isEnabled: true,
    merchantId: 'acct_1Mv8s92eSathiUs',
    environment: 'PRODUCTION',
    transactionFeePercent: 2.9,
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD'],
    lastPingStatus: 'HEALTHY'
  },
  {
    id: 'gw-razorpay',
    provider: 'RAZORPAY',
    name: 'Razorpay India Payment Engine',
    isEnabled: true,
    merchantId: 'rzp_live_SathiInd9012',
    environment: 'PRODUCTION',
    transactionFeePercent: 2.0,
    supportedCurrencies: ['INR', 'USD'],
    lastPingStatus: 'HEALTHY'
  },
  {
    id: 'gw-wallet',
    provider: 'WALLET',
    name: 'Sathi Direct Escrow Wallet',
    isEnabled: true,
    merchantId: 'vault_internal_sathi_00',
    environment: 'PRODUCTION',
    transactionFeePercent: 0.0,
    supportedCurrencies: ['USD', 'INR', 'EUR', 'GBP'],
    lastPingStatus: 'HEALTHY'
  },
  {
    id: 'gw-upi',
    provider: 'UPI',
    name: 'UPI Instant QR Gateway',
    isEnabled: true,
    merchantId: 'merchant.sathi@icici',
    environment: 'PRODUCTION',
    transactionFeePercent: 0.0,
    supportedCurrencies: ['INR'],
    lastPingStatus: 'HEALTHY'
  },
  {
    id: 'gw-card',
    provider: 'CREDIT_CARD',
    name: 'Visa / Mastercard / Amex Direct Merchant',
    isEnabled: true,
    merchantId: 'merch_card_9918231',
    environment: 'PRODUCTION',
    transactionFeePercent: 2.5,
    supportedCurrencies: ['USD', 'EUR', 'GBP', 'INR', 'JPY'],
    lastPingStatus: 'HEALTHY'
  }
];
