import {
  CategoryItem,
  ServiceItem,
  PricingProfile,
  RulesProfile,
  PolicyItem,
  RiskLevelItem,
  VerificationProfileItem,
  SafetyProfileItem,
  BookingRuleItem,
  EligibilityProfileItem
} from './types/serviceHub';

export const DEFAULT_PRICING_PROFILES: PricingProfile[] = [
  {
    id: 'pr-hourly-std',
    name: 'Standard Hourly Profile',
    pricing_type: 'Hourly',
    base_price: 500,
    currency: 'INR',
    minimum_duration: 1,
    maximum_duration: 12,
    extra_hour_price: 450,
    travel_charge: 100,
    platform_fee: 15,
    companion_commission: 85,
    tax: 18,
    weekend_multiplier: 1.15,
    holiday_multiplier: 1.25,
    surge_enabled: true,
    surge_rules: { peakHoursStart: '18:00', peakHoursEnd: '23:00', surgeMultiplier: 1.2 },
    cancellation_fee: 100,
    no_show_fee: 500,
    status: 'ACTIVE'
  },
  {
    id: 'pr-event-pro',
    name: 'Premium Event Package Profile',
    pricing_type: 'Per Event',
    base_price: 3500,
    currency: 'INR',
    minimum_duration: 4,
    maximum_duration: 10,
    extra_hour_price: 600,
    travel_charge: 250,
    platform_fee: 15,
    companion_commission: 85,
    tax: 18,
    weekend_multiplier: 1.2,
    holiday_multiplier: 1.3,
    surge_enabled: false,
    cancellation_fee: 500,
    no_show_fee: 1500,
    status: 'ACTIVE'
  },
  {
    id: 'pr-fixed-budget',
    name: 'Budget Fixed Profile',
    pricing_type: 'Fixed Price',
    base_price: 350,
    currency: 'INR',
    minimum_duration: 1,
    maximum_duration: 4,
    extra_hour_price: 300,
    travel_charge: 50,
    platform_fee: 10,
    companion_commission: 90,
    tax: 18,
    weekend_multiplier: 1.0,
    holiday_multiplier: 1.1,
    surge_enabled: false,
    cancellation_fee: 50,
    no_show_fee: 200,
    status: 'ACTIVE'
  }
];

export const DEFAULT_RULES_PROFILES: RulesProfile[] = [
  {
    id: 'rl-std-safety',
    name: 'Standard Operational Rules',
    description: 'Basic duration, age, and location verification rules',
    status: 'ACTIVE',
    rules: [
      {
        id: 'r-101',
        name: 'Duration Max Threshold',
        rule_type: 'Duration Rule',
        description: 'Bookings longer than 8 hours require explicit admin approval',
        condition: 'duration_hours',
        operator: 'GREATER_THAN',
        value: 8,
        action: 'REQUIRE_APPROVAL',
        severity: 'MEDIUM',
        status: 'ACTIVE'
      },
      {
        id: 'r-102',
        name: 'Live Location Permission Required',
        rule_type: 'Location Rule',
        description: 'Mandatory live GPS streaming during offline sessions',
        condition: 'live_location_enabled',
        operator: 'EQUALS',
        value: false,
        action: 'BLOCK',
        severity: 'HIGH',
        status: 'ACTIVE'
      }
    ]
  }
];

export const DEFAULT_POLICIES: PolicyItem[] = [
  {
    id: 'pol-std-v1',
    name: 'Standard Companion Policy v1.0',
    description: 'Standard usage policy, public place rules, and mandatory check-in protocol',
    version: 1,
    status: 'PUBLISHED',
    effective_from: '2026-01-01T00:00:00.000Z',
    minimum_age: 18,
    kyc_required: true,
    background_check_required: false,
    emergency_contact_required: true,
    public_location_only: true,
    live_location_required: true,
    sos_required: true,
    chat_moderation_required: true,
    incident_reporting_enabled: true,
    consent_required: true,
    prohibited_activity_text: 'Strictly no illegal activities, private residential meetings without prior verification, or unsafe environments.',
    versions: [
      {
        version: 1,
        effective_from: '2026-01-01T00:00:00.000Z',
        description: 'Initial release of Standard Companion Safety Policy',
        prohibited_activity_text: 'Strictly no illegal activities or private non-verified locations.'
      }
    ]
  }
];

export const DEFAULT_RISK_LEVELS: RiskLevelItem[] = [
  {
    id: 'rk-low',
    name: 'Low Risk',
    code: 'LOW',
    score: 10,
    description: 'Basic verification and safety controls required.',
    color: 'emerald',
    verification_level: 'Basic',
    monitoring_level: 'Standard',
    manual_approval_required: false,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 12,
    status: 'ACTIVE'
  },
  {
    id: 'rk-med',
    name: 'Medium Risk',
    code: 'MEDIUM',
    score: 35,
    description: 'Additional verification and periodic check-in monitoring.',
    color: 'amber',
    verification_level: 'Standard',
    monitoring_level: 'Enhanced',
    manual_approval_required: false,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 8,
    status: 'ACTIVE'
  },
  {
    id: 'rk-high',
    name: 'High Risk',
    code: 'HIGH',
    score: 65,
    description: 'Enhanced background verification and manual admin approval.',
    color: 'rose',
    verification_level: 'Enhanced',
    monitoring_level: 'Strict',
    manual_approval_required: true,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 6,
    status: 'ACTIVE'
  },
  {
    id: 'rk-crit',
    name: 'Critical Risk',
    code: 'CRITICAL',
    score: 90,
    description: 'Restricted service requiring strict admin sign-off and continuous monitoring.',
    color: 'purple',
    verification_level: 'Restricted',
    monitoring_level: 'Continuous',
    manual_approval_required: true,
    live_location_required: true,
    emergency_contact_required: true,
    sos_required: true,
    maximum_booking_duration: 4,
    status: 'ACTIVE'
  }
];

export const DEFAULT_VERIFICATION_PROFILES: VerificationProfileItem[] = [
  {
    id: 'vf-basic',
    name: 'Basic Verification Profile',
    description: 'Email, mobile, government ID, and selfie check',
    verification_level: 'Basic',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: false,
      address: false,
      background_check: false,
      emergency_contact: true,
      additional_document: false,
      manual_review: false
    }
  },
  {
    id: 'vf-standard',
    name: 'Standard Verification Profile',
    description: 'Basic verification + face match and address proof',
    verification_level: 'Standard',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: true,
      address: true,
      background_check: false,
      emergency_contact: true,
      additional_document: false,
      manual_review: false
    }
  },
  {
    id: 'vf-enhanced',
    name: 'Enhanced Verification Profile',
    description: 'Standard + background check and additional credentials',
    verification_level: 'Enhanced',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: true,
      address: true,
      background_check: true,
      emergency_contact: true,
      additional_document: true,
      manual_review: false
    }
  },
  {
    id: 'vf-restricted',
    name: 'Restricted Service Verification Profile',
    description: 'Enhanced verification + manual admin review',
    verification_level: 'Restricted',
    status: 'ACTIVE',
    requirements: {
      email: true,
      mobile: true,
      government_id: true,
      selfie: true,
      face_match: true,
      address: true,
      background_check: true,
      emergency_contact: true,
      additional_document: true,
      manual_review: true
    }
  }
];

export const DEFAULT_SAFETY_PROFILES: SafetyProfileItem[] = [
  {
    id: 'sf-std-controls',
    name: 'Standard Safety & Trust Profile',
    description: 'Full active safety suite including SOS, live location, and check-in/out',
    status: 'ACTIVE',
    controls: {
      sos: 'Required',
      emergency_contact: 'Required',
      live_location: 'Required',
      periodic_checkin: 'Required',
      booking_start_checkin: 'Required',
      booking_end_checkout: 'Required',
      geofence: 'Enabled',
      safe_location_requirement: 'Required',
      public_place_requirement: 'Required',
      emergency_notification: 'Enabled',
      admin_emergency_escalation: 'Enabled',
      incident_reporting: 'Enabled',
      chat_monitoring: 'Enabled',
      location_monitoring: 'Required'
    }
  }
];

export const DEFAULT_BOOKING_RULES: BookingRuleItem[] = [
  {
    id: 'bk-std-rule',
    name: 'Standard Booking & Cancellation Policy',
    min_advance_hours: 2,
    max_advance_days: 30,
    min_duration_hours: 1,
    max_duration_hours: 12,
    same_day_allowed: true,
    instant_booking_allowed: true,
    companion_approval_required: true,
    user_approval_required: false,
    cancellation_rules: {
      free_cancellation_window_hours: 24,
      tiers: [
        { hoursBeforeBooking: 24, refundPercentage: 100, cancellationFeePercent: 0 },
        { hoursBeforeBooking: 12, refundPercentage: 75, cancellationFeePercent: 25 },
        { hoursBeforeBooking: 2, refundPercentage: 50, cancellationFeePercent: 50 }
      ],
      no_show_refund_percent: 0
    },
    status: 'ACTIVE'
  }
];

export const DEFAULT_ELIGIBILITY_PROFILES: EligibilityProfileItem[] = [
  {
    id: 'eg-std-profile',
    name: 'Standard Companion Eligibility Profile',
    description: 'Age 18+, rating 4.0+, verified KYC & emergency contact',
    minimum_age: 18,
    maximum_age: 75,
    minimum_rating: 4.0,
    minimum_bookings_done: 0,
    required_documents: ['GOVERNMENT_ID', 'SELFIE_LIVE', 'EMERGENCY_CONTACT'],
    status: 'ACTIVE'
  }
];

export const INITIAL_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-1',
    name: 'Events & Social',
    slug: 'events-social',
    short_description: 'Corporate galas, weddings, networking expos & social gatherings',
    description: 'Professional companion support for formal events, award ceremonies, and family celebrations.',
    icon: 'Users',
    banner_image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    display_order: 1,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-event-pro',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-2',
    name: 'Travel & Exploration',
    slug: 'travel-exploration',
    short_description: 'Local city guides, road trips, food crawls & sightseeing',
    description: 'Explore new cities safely with trusted local guides, translators, and travel buddies.',
    icon: 'Compass',
    banner_image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80',
    display_order: 2,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-med',
    default_verification_profile_id: 'vf-enhanced',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-3',
    name: 'Care & Assistance',
    slug: 'care-assistance',
    short_description: 'Compassionate assistance for senior citizens & medical visits',
    description: 'Gentle companionship, hospital navigation, grocery errands, and elderly support.',
    icon: 'Heart',
    banner_image: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80',
    display_order: 3,
    status: 'ACTIVE',
    is_featured: true,
    minimum_age: 25,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-enhanced',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-4',
    name: 'Study, Career & Work',
    slug: 'study-career-work',
    short_description: 'Productivity partner, library buddy & cafe co-working',
    description: 'Stay focused with accountability companions for exam prep, brainstorming, and remote work.',
    icon: 'BookOpen',
    banner_image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
    display_order: 4,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-5',
    name: 'Fitness, Sports & Outdoor',
    slug: 'fitness-sports-outdoor',
    short_description: 'Workout spotting, running, cycling & sports partner',
    description: 'Jogging pacing buddies, gym weightlifting spotters, tennis partners, and trail hikers.',
    icon: 'Activity',
    banner_image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    display_order: 5,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 20,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-med',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-6',
    name: 'Gaming & Entertainment',
    slug: 'gaming-entertainment',
    short_description: 'Co-op gaming, esports, movie companions & Discord voice',
    description: 'Online gaming partners for ranked FPS, RPG co-op play, and movie viewing companions.',
    icon: 'Gamepad',
    banner_image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    display_order: 6,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-7',
    name: 'Social & Lifestyle',
    slug: 'social-lifestyle',
    short_description: 'Coffee conversations, dining partners & shopping assistance',
    description: 'Polite conversation partners for dining out, coffee breaks, and shopping trips.',
    icon: 'Coffee',
    banner_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80',
    display_order: 7,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-8',
    name: 'Pets & Hobbies',
    slug: 'pets-hobbies',
    short_description: 'Dog walking, photography companion, art & crafting buddy',
    description: 'Enthusiastic companions for pet walks, photography expeditions, and creative hobbies.',
    icon: 'Dog',
    banner_image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&auto=format&fit=crop&q=80',
    display_order: 8,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-9',
    name: 'Technology & Digital',
    slug: 'technology-digital',
    short_description: 'Tech setup support, digital literacy & gadget tutoring',
    description: 'Help with smart device setup, smartphone learning, and tech troubleshooting.',
    icon: 'Laptop',
    banner_image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    display_order: 9,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-10',
    name: 'Wellness & Mindfulness',
    slug: 'wellness-mindfulness',
    short_description: 'Meditation partner, nature walk companion & relaxation',
    description: 'Peaceful companions for yoga sessions, park meditation, and stress-free walks.',
    icon: 'Sun',
    banner_image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&auto=format&fit=crop&q=80',
    display_order: 10,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 20,
    default_pricing_profile_id: 'pr-hourly-std',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-11',
    name: 'Home & Personal Assistance',
    slug: 'home-personal-assistance',
    short_description: 'Errand assistance, home organizing & queue standing',
    description: 'Help with administrative queues, home organizing, and personal task execution.',
    icon: 'Home',
    banner_image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
    display_order: 11,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 21,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-standard',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cat-12',
    name: 'Community & Volunteering',
    slug: 'community-volunteering',
    short_description: 'Social causes, beach cleanups & shelter volunteering',
    description: 'Join community outreach projects, animal rescue events, and environmental cleanups.',
    icon: 'Globe',
    banner_image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&auto=format&fit=crop&q=80',
    display_order: 12,
    status: 'ACTIVE',
    is_featured: false,
    minimum_age: 18,
    default_pricing_profile_id: 'pr-fixed-budget',
    default_rules_id: 'rl-std-safety',
    default_policy_id: 'pol-std-v1',
    default_risk_level_id: 'rk-low',
    default_verification_profile_id: 'vf-basic',
    default_safety_profile_id: 'sf-std-controls',
    default_booking_rule_id: 'bk-std-rule',
    default_eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z'
  }
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-101',
    category_id: 'cat-1',
    category_name: 'Events & Social',
    name: 'Corporate Gala & Expo Companion',
    slug: 'corporate-gala-expo',
    short_description: 'Polite, well-mannered companion for networking dinners and galas',
    description: 'Professional presence at business conferences, networking expos, and formal galas under full escrow protection.',
    icon: 'Sparkles',
    display_order: 1,
    status: 'PUBLISHED',
    is_featured: true,
    minimum_age: 21,
    maximum_age: 65,
    online_allowed: false,
    offline_allowed: true,
    location_required: true,
    duration_required: true,
    risk_level_id: 'rk-low',
    pricing_profile_id: 'pr-event-pro',
    rules_profile_id: 'rl-std-safety',
    policy_id: 'pol-std-v1',
    verification_profile_id: 'vf-standard',
    safety_profile_id: 'sf-std-controls',
    booking_rule_id: 'bk-std-rule',
    eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-10T00:00:00.000Z',
    updated_at: '2026-01-10T00:00:00.000Z'
  },
  {
    id: 'srv-102',
    category_id: 'cat-1',
    category_name: 'Events & Social',
    name: 'Wedding & Reception Companion',
    slug: 'wedding-reception-companion',
    short_description: 'Well-groomed guest companion for family weddings',
    description: 'Friendly, well-mannered social presence for wedding celebrations and family functions.',
    icon: 'Users',
    display_order: 2,
    status: 'PUBLISHED',
    is_featured: false,
    minimum_age: 21,
    maximum_age: 65,
    online_allowed: false,
    offline_allowed: true,
    location_required: true,
    duration_required: true,
    risk_level_id: 'rk-low',
    pricing_profile_id: 'pr-event-pro',
    rules_profile_id: 'rl-std-safety',
    policy_id: 'pol-std-v1',
    verification_profile_id: 'vf-standard',
    safety_profile_id: 'sf-std-controls',
    booking_rule_id: 'bk-std-rule',
    eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-10T00:00:00.000Z',
    updated_at: '2026-01-10T00:00:00.000Z'
  },
  {
    id: 'srv-201',
    category_id: 'cat-2',
    category_name: 'Travel & Exploration',
    name: 'Historical & Cultural Walking Tour',
    slug: 'historical-walking-tour',
    short_description: 'In-depth sightseeing guide and local expert',
    description: 'Explore monuments, museums, and hidden local alleys safely with GPS live tracking enabled.',
    icon: 'Compass',
    display_order: 1,
    status: 'PUBLISHED',
    is_featured: true,
    minimum_age: 21,
    maximum_age: 70,
    online_allowed: false,
    offline_allowed: true,
    location_required: true,
    duration_required: true,
    risk_level_id: 'rk-med',
    pricing_profile_id: 'pr-hourly-std',
    rules_profile_id: 'rl-std-safety',
    policy_id: 'pol-std-v1',
    verification_profile_id: 'vf-enhanced',
    safety_profile_id: 'sf-std-controls',
    booking_rule_id: 'bk-std-rule',
    eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-01-15T00:00:00.000Z',
    updated_at: '2026-01-15T00:00:00.000Z'
  },
  {
    id: 'srv-301',
    category_id: 'cat-3',
    category_name: 'Care & Assistance',
    name: 'Doctor Appointment & Hospital Escort',
    slug: 'doctor-hospital-escort',
    short_description: 'Gentle assistance for medical visits and hospital navigation',
    description: 'Help senior citizens navigate hospital registration, pharmacy visits, and doctor appointments.',
    icon: 'Heart',
    display_order: 1,
    status: 'PUBLISHED',
    is_featured: true,
    minimum_age: 25,
    maximum_age: 65,
    online_allowed: false,
    offline_allowed: true,
    location_required: true,
    duration_required: true,
    risk_level_id: 'rk-low',
    pricing_profile_id: 'pr-hourly-std',
    rules_profile_id: 'rl-std-safety',
    policy_id: 'pol-std-v1',
    verification_profile_id: 'vf-enhanced',
    safety_profile_id: 'sf-std-controls',
    booking_rule_id: 'bk-std-rule',
    eligibility_profile_id: 'eg-std-profile',
    created_at: '2026-02-01T00:00:00.000Z',
    updated_at: '2026-02-01T00:00:00.000Z'
  }
];
